### ISSUE TITLE
Agenda de Proyectos

### ISSUE THREAD

**Issue by sssurugi** [bireme/proethos#101]
En el rol de proyectos agendados para una determinada reunión, hay una colmna llamada "descript", pero nunca hay nada hay. Se saca?

**Comment by carlasaenz** [comment]
Esto es la descripción de la actividad. Simplemente que la columna no sale alineada: el título está más a la derecha que el contenido. Debe alinearse para no crear confusión ni dar la impresión de que algo está faltando.
