### ISSUE TITLE
Problema con la creación de nuevo usuario desde la portada

### ISSUE THREAD

**Issue by asael-silva** [bireme/proethos#103]
Al intentar insertar un nuevo usuario el sistema retorna un mensaje informando error como descripto abajo:

Usuario nuevo
Field 'us_codigo' doesn't have a default value
insert into usuario (us_nome, us_login, us_email, us_email_alt, us_senha, us_ativo, us_instituition, us_endereco, us_country, us_cadastro, us_perfil) values ('Asael Silva', '', 'gandhalf_thewhite@live.com', 'gandhalf_thewhite@live.com', 'meleca99', '-1', 'BIREME', 'Rua Botucatu, 862', '00040', '20150204', '')

**Comment by trivasf** [comment]
Hoy hice prueba de esto y sigue sin funcionar. 
El Sistema me da mensaje que si me deja crearlo
![usuario nuevo confirmacion sistema](https://cloud.githubusercontent.com/assets/10438244/6181708/ed2203ae-b2eb-11e4-9d30-af5f5f191bba.jpg)
Luego recibo el email para validar (aunque el Sistema sigue sin reconocer los acentos en espanhol)
![email confirmacion usuario nuevo](https://cloud.githubusercontent.com/assets/10438244/6181737/6c031bcc-b2ec-11e4-99f0-fca4c5697d85.jpg)
Pero luego al hacer click en el enlace para validar, me da el siguiente mensaje
![msj compu al validar email nuevo usuario](https://cloud.githubusercontent.com/assets/10438244/6181742/81a1f7be-b2ec-11e4-8acd-ae336492eabc.jpg)

**Comment by carlasaenz** [comment]
El sistema recientemente ha funcionado de manera errática al mandar emails a nuevos usuarios, aunque esto es algo que estaba funcionando perfectamente antes y aparentemente está funcionando bien ahora. El texto de los emails automáticos ha sido revisado para indicar que solo hace falta hacer clic en el link que está en el email, y que el contenido mismo de la website es irrelevante. Sin embargo, una tarea pendiente es cambiar esa website de modo que diga simplemente "Su cuenta de ProEthos ha sido activada."
