### ISSUE TITLE
Pruebas de seguridad para buscar vulnerabilidades del sistema

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/proethos#106]

**Comment by ovidiopadilla** [comment]
Perfecto, haré las pruebas de SQL Injection.

**Comment by ovidiopadilla** [comment]
Perfecto.

2015-02-05 7:44 GMT-06:00 Renato Murasaki <notifications@github.com>:

> Assigned #106 <https://github.com/bireme/proethos/issues/106> to
> @ovidiopadilla <https://github.com/ovidiopadilla>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bireme/proethos/issues/106#event-230760996>.
>



-- 
Ovidio Enrique Padilla García
Coordinador Tecnologías de Información
Biblioteca Médica Nacional
Bibliotecas Virtuales en Salud Honduras
Facultad de Ciencias Médicas UNAH
Observatorio de Recursos Humanos en Salud Honduras
Centro de Información Sobre Desastres Biblioteca Médica Nacional
Red Latinoamericana de Centros de Información en Gestión del Riesgo,
Desastres y Salud
Móvil: 504-33921384, Oficina: 504-22325804

**Comment by renatomurasaki** [comment]
Ovidio, lograste hacer estas pruebas?

**Comment by ovidiopadilla** [comment]
Hola Buen Día

Estoy haciendo pruebas Retano, Te enviare mis aportes al terminarlas.

Saludos

2015-09-09 6:22 GMT-06:00 Renato Murasaki <notifications@github.com>:

> Ovidio, lograste hacer estas pruebas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bireme/proethos/issues/106#issuecomment-138892172>.
>



-- 
Ovidio Enrique Padilla García
Coordinador Tecnologías de Información
Biblioteca Médica Nacional
Bibliotecas Virtuales en Salud Honduras
Facultad de Ciencias Médicas UNAH
Observatorio de Recursos Humanos en Salud Honduras
Centro de Información Sobre Desastres Biblioteca Médica Nacional
Red Latinoamericana de Centros de Información en Gestión del Riesgo,
Desastres y Salud
Móvil: 504-33921384,99190266 Oficina: 504-22325804

**Comment by ovidiopadilla** [comment]
Disculpa Renato

El 9 de septiembre de 2015, 8:22, Ovidio Padilla <ovidiopadilla@gmail.com>
escribió:

> Hola Buen Día
>
> Estoy haciendo pruebas Retano, Te enviare mis aportes al terminarlas.
>
> Saludos
>
> 2015-09-09 6:22 GMT-06:00 Renato Murasaki <notifications@github.com>:
>
>> Ovidio, lograste hacer estas pruebas?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/bireme/proethos/issues/106#issuecomment-138892172>.
>>
>
>
>
> --
> Ovidio Enrique Padilla García
> Coordinador Tecnologías de Información
> Biblioteca Médica Nacional
> Bibliotecas Virtuales en Salud Honduras
> Facultad de Ciencias Médicas UNAH
> Observatorio de Recursos Humanos en Salud Honduras
> Centro de Información Sobre Desastres Biblioteca Médica Nacional
> Red Latinoamericana de Centros de Información en Gestión del Riesgo,
> Desastres y Salud
> Móvil: 504-33921384,99190266 Oficina: 504-22325804
>



-- 
Ovidio Enrique Padilla García
Coordinador Tecnologías de Información
Biblioteca Médica Nacional
Bibliotecas Virtuales en Salud Honduras
Facultad de Ciencias Médicas UNAH
Observatorio de Recursos Humanos en Salud Honduras
Centro de Información Sobre Desastres Biblioteca Médica Nacional
Red Latinoamericana de Centros de Información en Gestión del Riesgo,
Desastres y Salud
Móvil: 504-33921384,99190266 Oficina: 504-22325804

**Comment by wilsonmoura** [comment]
Depricated version of ProEthos. New version available at https://github.com/bireme/proethos2
