### ISSUE TITLE
Disponibilizar el acceso publico de los protocolos de revisión

### ISSUE THREAD

**Issue by ovidiopadilla** [bireme/proethos#107]
Estudiar la posibilidad de habilitar el acceso a la búsqueda publica para verificación de los temas potenciales de investigación, para evitar la redundancia de protocolos

**Comment by carlasaenz** [comment]
Ovidio, no entiendo el issue. Los protocolos en proceso de revisión no son materia de acceso público. Es decir, no debemos confundir ProEthos con un registro de investigaciones (como REBEC, clinicaltrials.gov, etc). Se puede hacer una búsqueda pública de los protocolos aprobados en el registro. Si bien por ahora los registros son solo de ensayos clínicos, esto está cambiando rápidamente para incluir a todas las investigaciones que revisa un comité.
Más aún, la redundancia no es un problema porque no es tarea del comité de ética determinar las áreas de la investigación. Si los investigadores quieren evitar hacer investigaciones redundantes la manera de hacerlo no es mirando los protocolos que están en revisión en un comité, porque en primer lugar hay MILES de comités de ética, lo que de hecho también explica la necesidad de los registros. La otra manera de hacerlo es mirando las publicaciones porque los procesos de investigación y publicación son fluidos.
Creo por eso que debemos cerrar este issue.

**Comment by carlasaenz** [comment]
Discutido y aclarado con Ovidio, paso a cerrar el issue.
