### ISSUE TITLE
Seria bueno indicar la versión de PHP requerida en el README

### ISSUE THREAD

**Issue by viniciusbireme** [bireme/proethos#108]
Actualmente solo informa PHP.

**Comment by ovidiopadilla** [comment]
Si es importante

**Comment by renatomurasaki** [comment]
https://github.com/bireme/proethos/pull/109

**Comment by asael-silva** [comment]
Information was consolidated under Technical Installation Manual (and also the other 2 translations - spanish and portuguese) and removed from the README.md file.
