### ISSUE TITLE
Sistema no envía email a nuevos usuarios

### ISSUE THREAD

**Issue by carlasaenz** [bireme/proethos#110]
Está relacionado al #103 aunque es un issue distintos: Creé un nuevo usuario (el usuario es Yurani Sandoval) ayer pero ella sigue sin recibir el email con la confirmación. Cuando trato de crearlo nuevamente, el sistema indica que ya creó un usuario para ella.

**Comment by trivasf** [comment]
Lo mismo me paso a mi con mi usuario taniarivas@hotmail.com. Nunca recibi email de confirmacion aunque el sistema dice que ya existe.
T

**Comment by renatomurasaki** [comment]
Todavia la cuestión de e-mail esta pendiente, pero el nuevo usuario debería lograr loguearse en el sistema.

Renato

**Comment by carlasaenz** [comment]
No estoy segura, Renato, porque usé ese email para "olvido su contrasenha" y tampoco envío nada (a pesar de que, como cuando uno crea la cuenta, aparece la nota diciendo que el email ha sido enviado). Claro que el problema adicional es que realmente olvide la contrasenha así que no puedo entrar y probar. Tania, puedes probar con tu hotmail, simplemente entrando con el password que pusiste?

**Comment by trivasf** [comment]
Yo si pude entrar con mi Hotmail. Pero si me paso antes lo mismo que a ti. Que cuando hacia click en “olvido su contrasena” el Sistema nunca me envoi un email con la nueva contrasena.

Ahora si me deja entrar. 






From: carlasaenz
Sent: ‎Friday‎, ‎February‎ ‎27‎, ‎2015 ‎1‎:‎14‎ ‎PM
To: bireme/proethos
Cc: Tania Flores





No estoy segura, Renato, porque usé ese email para "olvido su contrasenha" y tampoco envío nada (a pesar de que, como cuando uno crea la cuenta, aparece la nota diciendo que el email ha sido enviado). Claro que el problema adicional es que realmente olvide la contrasenha así que no puedo entrar y probar. Tania, puedes probar con tu hotmail, simplemente entrando con el password que pusiste?

**Comment by trivasf** [comment]
Hola,

Olvide mencionar que mi Hotmail si funciona, pero abri una cuenta con mi tp_flores@mail.com y esa es la que sigue sin funcionar. Cuando pido que me envien mi password, el email me llega diciendo que tal como lo solicite se me ha enviado un email con la informacion de mi contrasena, pero ese email NUNCA llega!






From: carlasaenz
Sent: ‎Friday‎, ‎February‎ ‎27‎, ‎2015 ‎1‎:‎14‎ ‎PM
To: bireme/proethos
Cc: Tania Flores





No estoy segura, Renato, porque usé ese email para "olvido su contrasenha" y tampoco envío nada (a pesar de que, como cuando uno crea la cuenta, aparece la nota diciendo que el email ha sido enviado). Claro que el problema adicional es que realmente olvide la contrasenha así que no puedo entrar y probar. Tania, puedes probar con tu hotmail, simplemente entrando con el password que pusiste?

**Comment by trivasf** [comment]
Ya esta funcionando esto. Procedemos a cerrar este issue.
