### ISSUE TITLE
Al subir una propuesta, cuando uno sube un adjunto se borra lo que había ingresado en la página

### ISSUE THREAD

**Issue by carlasaenz** [bireme/proethos#111]
Debe poder haber la opción de "grabar" las Referencias bibliográficas, contacto, etc. antes de subir el adjunto, o alternativamente se debe subir los adjuntos ("Presentación de archivos") en una página separada.

**Comment by trivasf** [comment]
Esto continua sin funcionar. Si lleno el espacio de bibliografia, contacto cientifico y aval previo, y luego subo un documento, al regresar a esa pagina, toda la informacion que se habia ingresado desaparece.

**Comment by trivasf** [comment]
Sigue borrandose la info en la bibliografia, contacto cientifico y aval previo despues que se sube un archivo al ingresar una nueva propuesta

**Comment by trivasf** [comment]
Este issue continua. Luego de subir un archivo cuando se ingresa una nueva propuesta, la informacion que se habia llenado de bibliografia, contacto cientifico y aval se borra totalmente

**Comment by trivasf** [comment]
Solucionamos creando una septima pagina, para que lor archivos subidos se encuentren en una pagina aparte. Pendiente de solucionar

**Comment by trivasf** [comment]
Esto esta solucionado. Revisado nuevamente este dia. Cerramos issue.
