### ISSUE TITLE
Agregar calendario bajo "Registro Principal" - "Fecha de inicio" 

### ISSUE THREAD

**Issue by trivasf** [bireme/proethos#112]
No hay calendario al momento

**Comment by ReneFGJr** [comment]
Não entendi, em qual tela não existe o calendário?!

**Comment by trivasf** [comment]
Rene
Cuando un protocolo se presenta como ensayo clinico, bajo la pestaña "informacion adicional", esta "registro principal" y el menu con el listado de nombres de registros. Luego esta el espacio para entrar el numero de registro y luego el espacio para entrar la fecha de registro. Ahi se necesita un calendario porque al momento solo esta el espacio y el boton para incluir. Deberia haber un calendario para simplificar el ingreso de una fecha.
Gracias
Tania

Please pardon any typos. Sent from my iPhone.

**Comment by trivasf** [comment]
Aun no se ha agregado el calendario aqui

**Comment by renatomurasaki** [comment]
No hay calendario porque fue solicitado un campo de fecha abierto, teniendo en cuenta situaciones donde no se puede precisar el día.
