### ISSUE TITLE
Admin deberia poder agregar archivos a protocolos presentados

### ISSUE THREAD

**Issue by trivasf** [bireme/proethos#113]
Si el admin/comite pide al investigador algun archive adicional a los presentados en un protocolo, este deberia poder subirlos y agregarlos. Al momento no se puede hacer esto.

**Comment by ReneFGJr** [comment]
Esta é uma dúvida!

O investigador poderá subir novos documentos enquanto em avaliação?

O admin/secretaria tem a opção de subir novos documentos quando o protocolo está em avaliação.

**Comment by ReneFGJr** [comment]
![image](https://cloud.githubusercontent.com/assets/7451759/6756279/76f78720-cf07-11e4-9875-947753844c26.png)

**Comment by trivasf** [comment]
Rene
El admin deberia poder agregar documentos a protocolos en evaluacion. 
Gracias
Tania

Please pardon any typos. Sent from my iPhone.

**Comment by trivasf** [comment]
esta funcinand bien
