### ISSUE TITLE
Error in SQL syntax

### ISSUE THREAD

**Issue by carlasaenz** [bireme/proethos#114]
![image](https://cloud.githubusercontent.com/assets/10438060/6564442/eadd609c-c67e-11e4-936d-89ca1da78b4e.png)

**Comment by carlasaenz** [comment]
Aparece cuando trato de ir, bajo el menú especial del investigador, a system messages (en inglés).

**Comment by ReneFGJr** [comment]
Não consegui repetir o erro, poderia tentar replicar novamente!

**Comment by trivasf** [comment]
esto esta resuelt. el mensaje no aparece mas.
