### ISSUE TITLE
Revisor externo e interno deben poder declinar si se les pide revisar una propuesta

### ISSUE THREAD

**Issue by carlasaenz** [bireme/proethos#116]
Por ejemplo si están de vacaciones o de viaje. Esto está relacionado con el issue#42 sobre el cambio de revisor asignado. Si un revisor asignado (externo=ad hoc o interno=miembro) por algún motivo no puede hacer la revisión debe poder asignarse la revisión a otra persona.

**Comment by carlasaenz** [comment]
Por ahora la comunicación con el ad hoc (como con los demás miembros) solo es posible por medio de comentarios en el sistema. Sin embargo debe ser posible retirar oficialmente a un ad hoc del proceso de revisión (issue #42 ), por ejemplo si el ad hoc avisa que hay un conflicto de interés. Este issue también está relacionado con el #99

**Comment by ReneFGJ** [comment]
Rene Faustino Gabriel Junior		rene@sisdoc.com.br	23/03/2015	Asignado

**Comment by trivasf** [comment]
estamos esperado la nueva version donde esto ya esta funcionando esto. esperamos probarlo paracerar este issue

**Comment by ReneFGJ** [comment]
Ao clicar no termo "Asignado" pode-se declinar da avaliação
