### ISSUE TITLE
URGENTE de reparar! Acciones de monitoreo

### ISSUE THREAD

**Issue by trivasf** [bireme/proethos#117]
A continuacion les detallo los problemas actuales del flujo de monitoreo y dictamenes:

1. Para cada propuesta con decision, el investigador debe ver todas las opciones de monitoreo que el Sistema ofrece. Al momento, se debe hacer un "click" en "añadir nueva accion de monitoreo" para que las opciones aparezcan, pero esto deberia estar mas visible, sin necesidad de una accion para ver.  (Esto Carla lo menciono en el issue #52). Ahora mismo, ProEthos muestra las siguientes acciones de monitoreo:
-Presentar una enmienda
-Presentar eventos adversos serios/normales-
-Conclusión del estudio
-Reporte de acompañamiento anual/semestral
-Suspensión del estudio
-Cancelación del estudio
-Envío de otros documentos
Se debe agregar:
-Inicio de reclutamiento (el investigador debe poder hacer clic en una casilla que diga "Reclutamiento de participantes iniciado" / "Recruitment of participants started")
Solicitud de extension a la aprobacion (Los investigadores deben subir como pdf un formato que estará bajo plantillas / seguimiento. El comité debe luego poder emitir una decisión y enviar el dictamen respectivo)

Al momento, la unica accion de monitoreo que esta funcionando es la de "presentar evento adverso". Aunque esta opcion aun muestra las pestanas mencionadas en el issue #85, que no deberian aparecer aqui. Ver:
![segundo test del lunes 26_acciones monitoreo_presentar eventos adversos](https://cloud.githubusercontent.com/assets/10438244/6693201/39fcbd5a-cc9f-11e4-8674-c4c735b0c2ee.jpg)

El resto de opciones de monitoreo NO esta funcionando. Ver:
![segundo test del lunes 26_acciones monitoreo_cancelacion estudio](https://cloud.githubusercontent.com/assets/10438244/6693235/7a0431bc-cc9f-11e4-8be6-8eda8e4bb09d.jpg)
![segundo test del lunes 26_acciones monitoreo_conclusion estudio](https://cloud.githubusercontent.com/assets/10438244/6693238/7a070dec-cc9f-11e4-941a-1d0f29ec194b.jpg)
![segundo test del lunes 26_acciones monitoreo_conclusion estudio2](https://cloud.githubusercontent.com/assets/10438244/6693237/7a06c6f2-cc9f-11e4-81f4-bd9f134f7a49.png)
![segundo test del lunes 26_acciones monitoreo_envio otros documentos](https://cloud.githubusercontent.com/assets/10438244/6693236/7a05e3c2-cc9f-11e4-9215-b128d3c39d36.jpg)
![segundo test del lunes 26_acciones monitoreo_presentar enmienda](https://cloud.githubusercontent.com/assets/10438244/6693240/7a0791cc-cc9f-11e4-9f61-bb6dc77cbb75.jpg)
![segundo test del lunes 26_acciones monitoreo_presentar enmienda2](https://cloud.githubusercontent.com/assets/10438244/6693239/7a074294-cc9f-11e4-883a-103a260142f9.jpg)
![segundo test del lunes 26_acciones monitoreo_reporte acompanamiento](https://cloud.githubusercontent.com/assets/10438244/6693241/7a1202b0-cc9f-11e4-9ac8-cea504edc7ea.jpg)
![segundo test del lunes 26_acciones monitoreo_suspension estudio](https://cloud.githubusercontent.com/assets/10438244/6693242/7a14d2b0-cc9f-11e4-8361-2d750181eb26.jpg)

2. TODAS las propuestas con decision deben tener acceso a todas las acciones de monitoreo. Esto fue mencionado en el issue #62. 
Bajo el perfil de csaenzb@yahoo.com, hay 3 propuestas. Ver:
![protocolos aprobados](https://cloud.githubusercontent.com/assets/10438244/6693471/39b502c4-cca1-11e4-92ad-68031fbd3116.jpg)
Pero solamente  puede accederse a la propuesta "Segundo test del lunes 26", aun cuando hay 3 mas. Ver:
![segundo test del lunes 26_acciones monitoreo](https://cloud.githubusercontent.com/assets/10438244/6693609/33cc9ff6-cca2-11e4-8ba7-0af2ae38f2f8.jpg)

Al tratar de entrar a otra propuesta con decision bajo este perfil, no da la opcion de hacer ningun tipo de monitoreo. Ver:
![prueba del viernes 30_no opcion de monitoreo](https://cloud.githubusercontent.com/assets/10438244/6693499/67acb802-cca1-11e4-9bee-6771613d6e74.jpg)

**Comment by trivasf** [comment]
Las acciones de monitoreo aun no funcionan. La prueba "Marzo 26 2015" fue condicionalmente aprobada, pero cuando trato de entrar como investigador principal y realizar el seguimiento, no me da ninguna opcion, ver:
![no se puede hacer monitoreo2](https://cloud.githubusercontent.com/assets/10438244/6931657/6fb923c0-d7d5-11e4-96eb-b3449f2465f6.jpg)

**Comment by renatomurasaki** [comment]
No hay error en el sistema para las acciones de monitoreo. Lo que se necesita es configurar cada una las acciones de monitoreo, via adminsitración, para que se muestren los formularios. "Presentar eventos adversos serios/normales" está funcionando porque fue configurado durante el Taller.

**Comment by renatomurasaki** [comment]
Haremos la configuración de las acciones con Tania y Rene.

**Comment by renatomurasaki** [comment]
Después de hacer una configuración de prueba, la otras acciones de monitoreo tampoco funcionaron. Analisando la fuente del error.

**Comment by renatomurasaki** [comment]
Bug resuelto en 02011cf405a9f9d94e3bd5e4da7c6a364932184d y e3497245dc1f1655c8dde8be44ca045574dc0206.

Ahora hace falta configurar las acciones de monitoreo.

**Comment by renatomurasaki** [comment]
Problema resuelto y enseñado a Tania como hacer las configuraciones del flujo (paginas y formulario con campos) de las acciones de monitoreo,
