### ISSUE TITLE
contextualizar mensajes del sistema por pantalla para facilitar/mejorar traducciones 

### ISSUE THREAD

**Issue by trivasf** [bireme/proethos#120]
al hacer traducciones de mensajes a veces estos se despliegan en varias pantallas del sistema pero a veces los contextos no son los adecuados. al contextualizar los mensajes por pantalla evitaremos este problema.

**Comment by renatomurasaki** [comment]
Este issue está relacionado con el #75

**Comment by renatomurasaki** [comment]
Después del analisis, la conclusión es que el sistema utiliza la misma variable de mensaje para distintos contextos. Es necesario identificar cada local del sistema donde el mensaje no confiere con el contexto. Empezaremos con las indicaciones del issue #75.

**Comment by trivasf** [comment]
Se ha creaso una solucion al problema de las traducciones. Al buscar un campo o mensaje del sistema para crear una traduccion, la pantalla va a mostrar un listado de todas las paginas donde se encuentra el mensaje en edicion, para saber exactamente que textos seran afectados por una traduccion. Si se realiza que uno de los campos que seria afectado por una traduccion no debreria serlo o deberia tener una traduccion diferente, entonces se va a lampagina donde esta el termino que debe ser diferente, se inactiva el termino actual y se crea uno nuevo con la traduccion correcta. Revisado por mi, pero antes de cerrar lo conversamos con Carla al final de este dia.

**Comment by trivasf** [comment]
Solucionado. Debe incluirse la explicacion de como esto funciona en el manual del admin para evitar confusion. Cerramos.
