### ISSUE TITLE
Test Correo Electronico

### ISSUE THREAD

**Issue by ovidiopadilla** [bireme/proethos#121]
En la ultima Actualización de Proethos no esta funcionando el test de correo electronico

**Comment by renatomurasaki** [comment]
Ovidio, cual es el mensaje de error?

2015-04-09 14:57 GMT-03:00 ovidiopadilla <notifications@github.com>:

> En la ultima Actualización de Proethos no esta funcionando el test de
> correo electronico
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bireme/proethos/issues/121>.
>



-- 
Renato Murasaki

**Comment by ovidiopadilla** [comment]
Al realizar un test del método seleccionado por ejemplo el método 1 con SendMail, no hace el envío de prueba al correo

**Comment by ovidiopadilla** [comment]
Y al darle Clic sobre el Enlace SHOW LOG no tiene ningún efecto

**Comment by renatomurasaki** [comment]
Logramos reproducir el mismo problema.

2015-04-09 16:20 GMT-03:00 ovidiopadilla <notifications@github.com>:

> Y al darle Clic sobre el Enlace SHOW LOG no tiene ningún efecto
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bireme/proethos/issues/121#issuecomment-91332845>.
>



-- 
Renato Murasaki

**Comment by renatomurasaki** [comment]
Informacióin adicional: el mecanismo de prueba de envío de correo no
muestra el log, pero llego el correo electrónico enviado por ProEthos.
Contiene la string "Congratulations" e informa el método utilizado. En
ambiente de homologación, fue utilizado el método 2.

2015-04-10 10:48 GMT-03:00 Renato Toshiyuki Murasaki <
renato.murasaki@gmail.com>:

> Logramos reproducir el mismo problema.
>
> 2015-04-09 16:20 GMT-03:00 ovidiopadilla <notifications@github.com>:
>
>> Y al darle Clic sobre el Enlace SHOW LOG no tiene ningún efecto
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/bireme/proethos/issues/121#issuecomment-91332845>.
>>
>
>
>
> --
> Renato Murasaki
>



-- 
Renato Murasaki

**Comment by ovidiopadilla** [comment]
Yo hice la prueba y utilizo el metodo 1 con Sendmail. Y no recibi el correo de prueba

**Comment by trivasf** [comment]
Ovidio, has logrado revisar si esto esta funcionado ya para ti?

**Comment by ovidiopadilla** [comment]
Hola buen Día.

Estoy utilizando el Método 1, Utilizo Sendmail como Manejador de Correos.
El Test lo envía sin problemas, Pero para el Registro de nuevos usuario y
recuperación de Contraseña no envía los mensajes.

Saludos

El 20 de agosto de 2015, 6:30, Tania Flores <notifications@github.com>
escribió:

> Ovidio, has logrado revisar si esto esta funcionado ya para ti?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bireme/proethos/issues/121#issuecomment-132992015>.
>



-- 
Ovidio Enrique Padilla García
Coordinador Tecnologías de Información
Biblioteca Médica Nacional
Bibliotecas Virtuales en Salud Honduras
Facultad de Ciencias Médicas UNAH
Observatorio de Recursos Humanos en Salud Honduras
Centro de Información Sobre Desastres Biblioteca Médica Nacional
Red Latinoamericana de Centros de Información en Gestión del Riesgo,
Desastres y Salud
Móvil: 504-33921384,99190266 Oficina: 504-22325804

**Comment by trivasf** [comment]
Gracias Ovidio. Lo revisamos y te comentamos luego. Saludos.

**Comment by moacirmoda** [comment]
Ovidio,

Buenos días,

Usted podría intentar utilizar el método 2? Este es el método recomendado, tanto en la seguridad como para la facilidad de el mantenimiento.

Saludos

Moacir

**Comment by mspasgt** [comment]
En nuestro caso (MSPAS Guatemala) se tuvo de crear de nuevo la función enviaremail que usa la libreria de phpmailer para poder conectarnos a un SMTP que no use unicamente el puerto 25 y que ademoas utilice otro tipo de seguridad en la autenticación-

esto obviamente deshabiltia la funcionalidad de ser administrable desde el backend pero nos permite mayor capacidad de comunicación.

No usamos el metodo uno porque estos mensajes seguramente llegarán a la bandeja de spam o no serán recibidos.

cambiamos de la linea 22 a la linea 54 del archivo _class_email.php en la carpeta _class

y se coloco:

if ($type == 'AUTH') {
            $replay = trim($hd->email_replay);
            $email_to = $dd[0];            
            require_once ("./libs/email/PHPMailerAutoload.php");
            $mail = new PHPMailer;
            $mail->isSMTP();
            $mail->SMTPDebug = 0;
            $mail->Debugoutput = 'html';
            $from = "Proethos";
            $from_name = "Proethos";
            $mail->Host = "smtp.gmail.com"; //O EL SMTP QUE USEN
            $mail->Port = 465; //Puerto para conexiones SSL
            $mail->SMTPAuth = true; 
            $mail->Username = "test@test.com"; //usuario 
            $mail->Password = "password"; // contraseña
            $mail->setFrom($from, $from_name);
            $mail->SMTPSecure = 'ssl';
            $mail->FromName = $from_name;
            $mail->Subject = $assunto;
            $mail->From = $from;
            $mail->addAddress($to, '');
            $mail->Subject = $subject;
            $mail->AltBody = 'This is a plain-text message body';
            $mail->Body = $messagem ;
            $mail->msgHTML($messagem, dirname(__FILE__));
            if (!$mail->send()) {
                echo "Mailer Error: " . $mail->ErrorInfo;
            } else {
                echo "Message sent!";
            }

**Comment by wilsonmoura** [comment]
Depricated version of ProEthos. New version available at https://github.com/bireme/proethos2
