### ISSUE TITLE
Búsqueda de Protocolos incorrecta

### ISSUE THREAD

**Issue by ovidiopadilla** [bireme/proethos#122]
En las ultimas versiones de Proethos al realizar una busqueda de todos los protocolos desde cualquier  perfil del Investigador o comité antes al realizar una busqueda se mostraban todos los ptotocolos ahora aparece este error:

Fatal error: Call to a member function fetch() on a non-object in /usr/local/www/apache24/data/proethos/_include/sisdoc_sql.php on line 195

**Comment by trivasf** [comment]
Esto esta funcionando correctamente. Cerramos este issue
