### ISSUE TITLE
Calendario inabilitado

### ISSUE THREAD

**Issue by ovidiopadilla** [bireme/proethos#123]
En las Propuestas en proceso de revisión del comité del resumen de comité, después de ser aprobado el protocolo y al intentar asignar para reunión no despliega el calendario para confirmar la fecha de reunión y en versiones anteriores si se desplegaba.

**Comment by trivasf** [comment]
Ovidio, para que puedas asignar un protocol para revision en una reunion de comite, debes crear nuevas reunions del comite bajo el menu del administrador, luego tipos de calendario, y bajo calendario, vas y haces click en "novo" para crear una reunion nueva. 
Yo probe esta function y esta funcionando perfectamente. Por favor trata asi y si te funciona cerramos este isuse. Saludos.

**Comment by ovidiopadilla** [comment]
Bien socializare el comentario a los comités.

Gracias

El 13 de abril de 2015, 11:42, Tania Flores <notifications@github.com>
escribió:

> Ovidio, para que puedas asignar un protocol para revision en una reunion
> de comite, debes crear nuevas reunions del comite bajo el menu del
> administrador, luego tipos de calendario, y bajo calendario, vas y haces
> click en "novo" para crear una reunion nueva.
> Yo probe esta function y esta funcionando perfectamente. Por favor trata
> asi y si te funciona cerramos este isuse. Saludos.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bireme/proethos/issues/123#issuecomment-92442420>.
>



-- 
Ovidio Enrique Padilla García
Coordinador Tecnologías de Información
Biblioteca Médica Nacional
Bibliotecas Virtuales en Salud Honduras
Facultad de Ciencias Médicas UNAH
Observatorio de Recursos Humanos en Salud Honduras
Centro de Información Sobre Desastres Biblioteca Médica Nacional
Red Latinoamericana de Centros de Información en Gestión del Riesgo,
Desastres y Salud
Móvil: 504-33921384, Oficina: 504-22325804

**Comment by trivasf** [comment]
El issue se explico a Ovidio, y se reviso en el sistema y esta funcionando correctamente. Voy a cerrarlo entonces.
