### ISSUE TITLE
Co-Investigadores no visualizan protocolos

### ISSUE THREAD

**Issue by ovidiopadilla** [bireme/proethos#124]
Después de ingresar un protocolo por el investigador principal y este agrega co-investigadores que previamente ya están registrados en proethos, estos no pueden visualizar el proceso de las propuestas del protocolo en revisión, solamente el investigar principal puede hacerlo. Se recomienda agregar la funcionalidad de que los co-investigares puedan visualizar en avance de la revisión de los protocolos en los cuales están trabajando.

**Comment by trivasf** [comment]
Estamos trabajando en esto. El issue sera resuelto en los proximos dias.

**Comment by trivasf** [comment]
Este issue aun esta pendiente.Hicimos pruebas con Peru tambien y ellos tampoco pueden visualizar los protocolos en los que son co-investigadores.

**Comment by trivasf** [comment]
Este issue sera resuelto en la proxima actualizacion -

**Comment by wilsonmoura** [comment]
Depricated version of ProEthos. New version available at https://github.com/bireme/proethos2
