### ISSUE TITLE
Miembros de Comite y Co-investigador

### ISSUE THREAD

**Issue by ovidiopadilla** [bireme/proethos#125]
En ocasiones los miembros de comité de ética con co-investigares de un protocolo y el sistema no debería permitir que dichos miembros puedan ser revisores de ese protocolo en en cual están trabajando. Se recomienda agregar una función en la plataforma de restringir el acceso en ese caso. De la misma forma que ocurre cuando es investigador principal que no le es permitido revisar el protocolo aun cuando es miembro del comité de revisión.

**Comment by trivasf** [comment]
Hola Ovidio, un poco tarde esta contestación pero espero te sirva. 
Si un protocolo de investigación que se presenta para revisión incluye en si listado de investigadores el nombre de un miembro del comité, este miembro tendrá acceso limitado al protocolo y al proceso de revisión del mismo. Asi si un protocolo incluye tu nombre dentro del equipo de investigadores, aunque tengas perfil de admin, no podrás participar en el proceso de revisión del protocolo. El sistema no te lo permitira.

**Comment by trivasf** [comment]
Esta funcionalidad ya existe en el sistema. Cerramos el issue
