### ISSUE TITLE
Accion de monitoreo genera nuevo numero de protocolo

### ISSUE THREAD

**Issue by trivasf** [bireme/proethos#126]
Al hacer una nueva acción de monitoreo de un protocolo ya existente, el sistema le asigna un nuevo numero de protocolo al proyecto, aun cuando este ya tiene un numero asignado previamente. 
Esto va de la mano del issue #85

**Comment by renatomurasaki** [comment]
De hecho el sistema no está generando otro número de protocolo. Este número que aparece en las pantallas es un identificador único interno. Para no provocar confusiones, estos números serán sacados de las pantallas.
