### ISSUE TITLE
Actualizar script de creación del banco de datos.

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/proethos#127]
Evaluar si es necesario crear un patch de banco de datos.

**Comment by renatomurasaki** [comment]
Ya fue implementado, pero obliga en instalaciones ya existentes, despues de hacer un git pull, ejectuar en el Menu Administador la opción "Actualizar Sistema"

**Comment by renatomurasaki** [comment]
Es necesario actualizar el patch de banco, despues de la experiencia de instalación/actualización de la instancia de Colombia.

**Comment by wilsonmoura** [comment]
Depricated version of ProEthos. New version available at https://github.com/bireme/proethos2
