### ISSUE TITLE
Revisión de los mensajes que van por correo

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/proethos#129]

**Comment by renatomurasaki** [comment]
Comments from Tania -- "Los campos en los emails que pueden "autollenarse", es decir, que no haya necesidad de escribir por ejemplo el titulo del protocolo o el numero del protocolo, el nombre del comite, etc.
Mira esto por ejemplo. El titulo, nombre del protocolo, nombre del comite y en "link", seran automaticos en los emails."

**Comment by trivasf** [comment]
Ejemplo:
![issue 129](https://cloud.githubusercontent.com/assets/10438244/10104268/6d21d3f8-636e-11e5-9052-4a53e82afff7.jpg)

**Comment by moacirmoda** [comment]
Tania,

Buenos dias,

Usted podria mostrarme em cual etapa este email és enviado?

Saludos

**Comment by trivasf** [comment]
Hola Moacir,
Este mensaje en especial es el que recibe el AdHoc cuando se le asigna un protocolo para revision.
Pero creo que aca hay dos issues diferentes mencionados. El issue al que yo me referia con el screenshot es al issue #40 que habla de que pueden haber campos que se llenen automaticamente, como el nombre y numero de protocolo. Pero el issue #129 no se si se refiere a lo mismo. Ese ultimo issue no lo abri yo.

**Comment by moacirmoda** [comment]
@trivasf Hice algunas pruebas y los campos "autolleneranse" normalmente. Yo no entendi cuál es el problema con este tema.

@renatomurasaki tienes alguna idea de lo que ocurre?

**Comment by renatomurasaki** [comment]
@trivasf @carlasaenz ustedes tienen un correo recibido por la plataforma
donde estos campos no se autollenaron?

2015-09-29 15:39 GMT-03:00 Moacir Moda Neto <notifications@github.com>:

> @trivasf <https://github.com/trivasf> Hice algunas pruebas y los campos
> "autolleneranse" normalmente. Yo no entendi cuál es el problema con este
> tema.
>
> @renatomurasaki <https://github.com/renatomurasaki> tienes alguna idea de
> lo que ocurre?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bireme/proethos/issues/129#issuecomment-144150959>.
>



-- 
Renato Murasaki

**Comment by trivasf** [comment]
Renato
Estoy recibiendo todos los mensajes del sistema y estoy por enviarlos para que vean los campos que no se autollenan correctamente.
Tania

**Comment by trivasf** [comment]
Aca les adjunto un screenshot de uno de los emails recibidos por el sistema y que contiene campos que no se autollenan y tambien que siguen teniendo problema con los acentos de espanol:
![emails received](https://cloud.githubusercontent.com/assets/10438244/10485166/4d9a6880-724e-11e5-887e-89ba097dce5e.jpg)

**Comment by moacirmoda** [comment]
Criando ferramenta que corrige encoding errado de banco. (4ed643ae93c3b4ba8473e08036ee0f25ee6cef24)

https://github.com/bireme/proethos/wiki/Troubleshooting#fixing-system-encoding

Creio que seria interessante realizar este procedimento na base em que a Carla testou.

@carlasaenz Onde foi realizado o teste do print acima?

**Comment by carlasaenz** [comment]
Hola Moacir,
Copio a Tania para que dé la respuesta porque no sé dónde fue esta prueba.
Gracias!
Carla

Carla Saenz, PhD
Bioethics Regional Advisor
Knowledge Management, Bioethics and Research
Pan American Health Organization

**Comment by trivasf** [comment]
Estimados,
El screenshot que yo agregue en este issue, el ultimo, es de emails recibidos del sistema.
Cuando se asigna un revisor o cuando se emite una decision, el sistema envia un email automatico.
Los campos que deben llenarse automaticamente, como el nombre del autor, que en el email esta como $NAME, en realidad no reflejan el nombre del autor automaticamente.
Saludos,

Tania Flores
PAHO Consultant
ProEthos

ProEthos is an innovative platform for the ethics review of research with human subjects.
Learn more and download here<http://www.paho.org/proethos>.

________________________________

**Comment by moacirmoda** [comment]
​Tania,

Buenos dias,

Obrigado por las informaciones, pero yo necesito saber la url del proethos
que fue realizado sus testes.

Saludos,

Moacir​

**Comment by trivasf** [comment]
Hola Moacir,
Estos tests se han hecho en el ambiente de homologacion (http://proethos.homolog.bvsalud.org/login.php). De hecho, los emails que recibo como admin, vienen de tests que tu y/o Rene han realizado tambien.

Saludos,

Tania Flores
PAHO Consultant
ProEthos

ProEthos is an innovative platform for the ethics review of research with human subjects.
Learn more and download here<http://www.paho.org/proethos>.

________________________________

**Comment by moacirmoda** [comment]
Muchas gracias Tania.

Saludos

**Comment by wilsonmoura** [comment]
Depricated version of ProEthos. New version available at https://github.com/bireme/proethos2
