### ISSUE TITLE
Facilitar la identificación de los cambios en los metadatos, cuando se somete una acciones de monitoreo del tipo enmienda.

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/proethos#131]
Los metadatos de la enmienda son los mismos del estudio, pero algunos campos no serán editables. La idea es facilitar el trabajo de quien hará el análisis de la enmienda, informando cuales fueron los campos que sufrieron actualización. Los metadatos del estudio están armacenados e un registro independiente de la acción de monitoreo.

**Comment by renatomurasaki** [comment]
Se tomo la decisión que cualquier campo puede ser editado en la enmienda. Con eso, es fundamental que el sistema identifique cuales son los campos de la enmienda que fueron editados para facilitar el análisis del comité.

**Comment by trivasf** [comment]
Este issue sera trabajado por Moacir, de acuerdo a lo conversado con Rene. No podra solucionarse durante la reunion de Sao Paulo, pero Moacir trabajara en esto.

**Comment by renatomurasaki** [comment]
A cada sumisión de protocolo y enmienda un archivo XML é generado. Se debe generar un mecanismo de comparación de los campos XML de la enmienda con el protocolo o de la enmienda más reciente con la enmienda anterior. La comparación generará un archivo PDF con el resultado de la comparación.

**Comment by moacirmoda** [comment]
Eu creio que encontrei um bug. Quando submetemos um protocolo, ele é recusado, e o investigador o envia novamente, os novos documentos associados a este protocolo perdem a referência no banco de dados. Não consegui encontrar onde está este erro.

@ReneFGJ é realmente um bug?

**Comment by moacirmoda** [comment]
![sem titulo](https://cloud.githubusercontent.com/assets/549428/10207942/0b188a58-67a6-11e5-9faa-b74d49b0f3c0.png)

**Comment by wilsonmoura** [comment]
Depricated version of ProEthos. New version available at https://github.com/bireme/proethos2
