### ISSUE TITLE
Sacar el "número del protocolo" de todas las pantallas que se refieren al ID interno del sistema

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/proethos#132]
Sustituir este ID interno por la información del estudio o sacarlo, de acuerdo al contexto de la pantalla. Este ID provoca confusión cuando el estudio ya fue sometido y está en análisis interno.

**Comment by moacirmoda** [comment]
Alteração feita, favor verificar.

**Comment by trivasf** [comment]
Verificado. Cerramos issue.
