### ISSUE TITLE
Actualizacion del sistema en Colombia no funciona

### ISSUE THREAD

**Issue by trivasf** [bireme/proethos#133]
de Elizabeth Lopez, INS Colombia:

Le comento que la dificultad que tenemos con la implementación de Proethos está relacionada con el registro de los proyectos y es el siguiente:

El proceso de registro de los proyectos se realiza normalmente hasta llegar a la etapa de Programación para reunión. Cuando se programa para reunión se habilita la opción ESCRIBIR OPINION, esta opción habilita la opción de emitir la decisión final, con la que se abre un formulario que se diligencia y se guarda como Versión Final. Este genera un archivo que se carga dentro de los archivos del proyecto y  el estado del proyecto pasa a APROBADO, rechazado, etc según sea la decisión. Después de esta etapa no pasa a las siguientes y el sistema me permite seguir adicionando DECISIONES, que se van cargando a los archivos del proyecto y no pasa a las etapas de LISTO PARA DECISION e INVESTIGACION EN CURSO. De acuerdo con el correo recibido hicimos la actualización, pero el inconveniente persiste y no sabemos cuál es la causa. (Anexo enviamos los pantallazos donde se puede ver )

Hemos realizado varias pruebas en la plataforma que tienen dispuesta para esto y como vimos que tenía nuevas funcionalidades, el 25 de Agosto hicimos una nueva instalación, pero en esta nueva instalación al ingresar al sistema no carga la página inicial (HOME) y genera error cuando se ingresa con un usuario que no es administrador y al ingresar los proyectos tenemos el mismo inconveniente que en la otra instalación, es decir solo podemos llegar a la etapa de Programación para reunión. El Martes  8 de Septiembre realizamos otra instalación con la opción del paquete ZIP y presenta los mismos inconvenientes de la instalación del 25 de agosto.

**Comment by trivasf** [comment]
de Tania Flores:

Cabe la posibilidad que la actualizacion que se hizo en tu sistema no haya cargado correctamente?
Te comento esto porque algunos de los pantallazos que tu me enviaste, estan funcionando correctamente cuando yo entro al sistema a corroborar los problemas que tu me enviaste.
Te estoy adjuntando el documento en Word que me enviaste, y te he agregado mis comentarios en rojo, y los pantallazos que genera el sistema correctamente de mi parte.

Los archivos cargados no reflejados en el sistema, al igual que los protocolos estacionados en "programado para reunion" si estan presentes en mis pruebas tambien, y ya hice las consultas necesarias para encontrar una razon del porque estan sucediendo y como lo solucionaremos.

Valdria la pena actualizar el sistema una vez mas?

Al final del documento de Word te indico donde ir para la actualizacion. Espero que esto resuelva algunos de los problemas que has encontrado. De lo contrario, por favor me avisas y veremos que esta pasando entonces.

**Comment by trivasf** [comment]
de Elizabeth Lopez:
Tania buenas tardes:
 
Le comento que cuando hicimos la actualización de PROETHOS, no la realizamos desde el menú de administración, la hicimos con el comando GIT PULL en el servidor desde el directorio donde está la aplicación,  y nos generó un mensaje que nos indicaba que  los archivos de la carpeta messages, se debían proteger o renombrar antes de reemplazarlos.  Los renombramos y ejecutamos la actualización, pero no generó más mensajes de advertencia.
 
De acuerdo con sus indicaciones, hoy realizamos la actualización por el  Menú del Administrador y primero me generó error de permisos sobre la carpeta.
 
Cambiamos los permisos en la carpeta y ejecutamos nuevamente la opción y generó el siguiente pantallazo:
![update colombia](https://cloud.githubusercontent.com/assets/10438244/9880270/97ebb2a6-5b90-11e5-9015-9c812dc0b934.png)

Volvimos a ejecutar el comando y aparece el siguiente pantallazo:
![update colombia2](https://cloud.githubusercontent.com/assets/10438244/9880291/ab9be8e8-5b90-11e5-8afd-afbe75f15dc1.png)

Después de ejecutar está actualización realizamos nuevamente pruebas ingresando un nuevo proyecto, pero el resultado es el mismo;
Agradecemos su colaboración y quedamos pendientes de sus indicaciones,

**Comment by trivasf** [comment]
Argentina tampoco ha podido actualizar exitosamente el sistema.

**Comment by renatomurasaki** [comment]
Tania, son problemas distintos. Se necesita crear otro issue para el caso
de Argentina.

2015-09-16 13:36 GMT-03:00 Tania Flores <notifications@github.com>:

> Argentina tampoco ha podido actualizar exitosamente el sistema.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bireme/proethos/issues/133#issuecomment-140796787>.
>



-- 
Renato Murasaki

**Comment by trivasf** [comment]
De acuerdo. Voy a abrir un isue nuevo.
Gracias!

Tania Flores
Consultant
ProEthos

ProEthos is an innovative platform for the ethics review of research with human subjects.
Learn more and download here<http://www.paho.org/proethos>.

________________________________

**Comment by renatomurasaki** [comment]
Necesario arreglar el banco de datos, teniendo en cuenta que la última versión del sistema presenta cambios de estructura de datos. Issue #127

**Comment by trivasf** [comment]
Se creara una actualizacion para la base de datos para solucionar estos problemas. Estimamos que para el lunes 28 de diciembre podremos comunicar a los paises que hagan una actualizacion desde el menu especial del administrador para solucionar estos issues. (En base a Skype con Rene este dia)

**Comment by wilsonmoura** [comment]
Depricated version of ProEthos. New version available at https://github.com/bireme/proethos2
