### ISSUE TITLE
Todos los protocolos quedan en "programado para reunion", aunque ya tengan dictamen final subido

### ISSUE THREAD

**Issue by trivasf** [bireme/proethos#135]
![programado para reunion](https://cloud.githubusercontent.com/assets/10438244/9880812/e948ee6e-5b92-11e5-8004-c36633a7581a.jpg)

**Comment by trivasf** [comment]
Este problema continua igual

**Comment by trivasf** [comment]
Esto al pacerer ya esta funcionando correctamente. En base a mis pruebas. No voy a cerrar el issue hasta hablar con Colombia para confirmar que ellos tambien pueden ver este proceso correctamente.

**Comment by ReneFGJr** [comment]
Olá Tania,

pode-se clicar no menu do administrador, nesta tela o sistema cria o botão de finalização

![image](https://cloud.githubusercontent.com/assets/7451759/11733655/c88ae39c-9f96-11e5-959b-ffe12121bc29.png)

**Comment by trivasf** [comment]
Hola Rene,

Este problema lo tiene Colombia desde hace meses.
Ellos ya hicieron esto de hacer click en actualizar sistema, pero no se resuelve.
Que otra cosa puede estar pasando?
Gracias por tu ayuda!

Tania Flores
ProEthos Consultant
Knowledge Management, Bioethics and Research
Pan American Health Organization


ProEthos is an innovative platform for the ethics review of research with human subjects.
Learn more and download here<http://www.paho.org/proethos>.

________________________________

**Comment by ReneFGJr** [comment]
Olá Tania,

foi cambiado o label da botao de "finalizado" para "send to secretary", para que o parecer seja revisado e encaminhado. 

Clicando neste botão o sistema vai para a "pantalha" correta.
