### ISSUE TITLE
Actualizacion del sistema en Argentina no funciona

### ISSUE THREAD

**Issue by trivasf** [bireme/proethos#137]
IT de Argentina se comunicara directamente con Bireme para explicar (de acuerdo a email de Laura Antonietti del dia 16 de septiembre 2015.

**Comment by renatomurasaki** [comment]
Esperando respuesta del equipo de Argentina, si llegaron a oprimir el enlace “admin_message_create” que aparece en el area de administración de ProEthos.

Bajando para severity 2, porque el error está en un ambiente de homologación y el sistema en producción continua funcionando en la versión anterior.

**Comment by renatomurasaki** [comment]
Solicitando dump de la tabla _messages de la instancia de Argentina para análisis.

**Comment by wilsonmoura** [comment]
Depricated version of ProEthos. New version available at https://github.com/bireme/proethos2
