### ISSUE TITLE
Implementar la pantalla de presentación de una enmienda

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/proethos#138]
Traer en los pasos 1, 2 y 3 de la acción de monitoreo "Presentrar una enmienda", los campos del protocolo original.

**Comment by renatomurasaki** [comment]
Se tomó la decisión con Carla y Tania que en la presentación de una enmienda, la pantalla tendrá las mismas 7 pestañas de la presentación del protocolo. En este momento, la pantalla debe tener los campos cargados con los datos originales para que el investigador pueda cambiar solamente los campos necesarios. Un archivo PDF será generado con la enmienda y un archivo XML interno también para facilitar la identificación de los cambios entre el protocolo original y la enmienda (#131).

**Comment by renatomurasaki** [comment]
@ReneFGJ @moacirmoda - necesitamos retomar este issue porque la implementación del #131 depende de la resolución de la pantalla de sumisión de la enmienda.

**Comment by trivasf** [comment]
Este issue sigue pendiente. La presentacion de enmienda solo permite tres campos al momento. Manana martes 5 de enero lo veremos con Rene nuevamente para solucionar.

**Comment by wilsonmoura** [comment]
Depricated version of ProEthos. New version available at https://github.com/bireme/proethos2
