### ISSUE TITLE
Idioma predeterminado al inicio del download no puede cambiarse en El Salvador

### ISSUE THREAD

**Issue by trivasf** [bireme/proethos#139]
El comite de etica de El Salvador, al momento de bajar el software, dejo el idioma ingles como el predeterminado en el sistema. Luego quisieron cambiarlo yendo al menu del administrador - personalizar informacion del comite - preferencia de idioma; pero aun despues de actualizar el cambio este no se refleja.

**Comment by trivasf** [comment]
El sistema esta en la version correcta (version: v.0.15.05), pero no permite el cambio de idioma, y todos los campos se muestran sin las traducciones que ya estan hechas en el sistema.
Ver:
![el salvador](https://cloud.githubusercontent.com/assets/10438244/10024033/cec3cc2a-611a-11e5-9e5b-dfb412b224d8.jpg)

![el salvador2](https://cloud.githubusercontent.com/assets/10438244/10024039/d47d8f7a-611a-11e5-9a63-e7b37e66c8d7.jpg)

**Comment by trivasf** [comment]
He sugerido a El Salvador que desinstalen el sistema y lo vuelvan a instalar para que el idioma quede predeterminado al espanol, ya que el comite necesita entrenarse en el sistema y no manejan el idioma ingles bien. Sin embargo, creo que esto es un issue que tenemos que solucionar, pues deberia el sistema permitir el cambio de idioma predeterminado aun cuando inicialmente se haya escogido un idioma X.

**Comment by renatomurasaki** [comment]
Para volver las traducciones de los labels, por favor, oprimir el enlace “admin_message_create” que aparece en el area de administración de ProEthos.

**Comment by trivasf** [comment]
Gracias Renato,

Estoy buscando el enlace que lee “admin_message_create”, pero no logro encontrarlo. Mira:
[X]
[X]

Me ayudas por fa? Mil gracias!

Tania Flores
Consultant
ProEthos

ProEthos is an innovative platform for the ethics review of research with human subjects.
Learn more and download here<http://www.paho.org/proethos>.

________________________________

**Comment by trivasf** [comment]
No veo el enlace para “admin_message_create”

![menu admin 1](https://cloud.githubusercontent.com/assets/10438244/10398406/6b07c91a-6e72-11e5-8772-eeddd6b3a3ef.jpg)

![menu admin 2](https://cloud.githubusercontent.com/assets/10438244/10398411/701c4002-6e72-11e5-9e08-b2862e6093a9.jpg)

**Comment by renatomurasaki** [comment]
Tania, mirando la pantalla https://cloud.githubusercontent.com/assets/10438244/10024039/d47d8f7a-611a-11e5-9a63-e7b37e66c8d7.jpg, se logra ubicar este enlace en la sección admin_menu_special > admin_message.

Mirando la pantalla https://cloud.githubusercontent.com/assets/10438244/10398411/701c4002-6e72-11e5-9e08-b2862e6093a9.jpg, el mismo enlace se muestra "traducido" para "Atualizar mensagens do sistema". Creo que las pantallas muestran situaciones distintas, dependiendo del idioma de la interfaz.

**Comment by trivasf** [comment]
Gracias Renato. Converse con El Salvador sobre esto, ellos haran lo que indicaste y estoy solamente a la espera que me confirmen que esta funcionando bien el idioma ahora.

**Comment by trivasf** [comment]
Ovidio Padilla de Honduras nos ayudo a reinstalar el sistema en El Salvador. Al momento no he sabido nada departe del comite de si esta funcionando mal o bien. Pedi acceso al sistema para realizar pruebas y esta semana actualizo este issue para ver si ya podemos cerrarlo.

**Comment by trivasf** [comment]
El sistema ha logrado ser instalado exitosamente. El idioma esta funcionando correctamente, aunque hay otros issues en los que se esta trabajando al momento. Me he contactado con El Salvador y con Ovidio Padilla de Honduras, quien es quien nos esta apoyando con esto. Cerramos este issues pues el idioma se soluciono.
