### ISSUE TITLE
El perfil de coordenador no esta funcionando

### ISSUE THREAD

**Issue by trivasf** [bireme/proethos#143]
Al querer trabajar en el sistema bajo el perfil de Coordenador, el sistema primero muestra la pantalla como perfil de comite, Ver:
![coordenador](https://cloud.githubusercontent.com/assets/10438244/10942941/d45548ce-82d7-11e5-816c-5a658995f049.jpg)

Pero luego, al querer entrar a ver los protocolos, la pantalla se queda en blanco. Ver:
![coordenador2](https://cloud.githubusercontent.com/assets/10438244/10942948/e3b5d496-82d7-11e5-9851-2b1cc0d1d3cb.jpg)

**Comment by moacirmoda** [comment]
Tania,

Buenos dias,

Yo intenté reproduzir el error, pero aca me parece normal.
![captura de tela de 2015-11-05 10 33 51](https://cloud.githubusercontent.com/assets/549428/10968520/e2f46a5a-83a8-11e5-9927-90d1e5b20937.png)

**Comment by trivasf** [comment]
Hola Moacir,
Yo todavía no puedo ver nada con el perfil de coordinador.
Quiza podamos verlo hoy durante nuestra reunion rapidito, o si no, la próxima semana.
Abrazo

Tania Flores
PAHO Consultant
ProEthos

ProEthos is an innovative platform for the ethics review of research with human subjects.
Learn more and download here<http://www.paho.org/proethos>.

________________________________

**Comment by moacirmoda** [comment]
Tania,

Buenos dias,

Yo voy solicitar a @viniciusandrade los logs de errores para analisar o que esta ocurriendo.

@viniciusandrade você pode me mandar os logs de erro da instância de homolog do proethos do dia 4/11/2015?

Abraços

**Comment by viniciusandrade** [comment]
@moacirmoda,

Archivos de log enviados para su email.

Saludos
Vinicius

**Comment by ReneFGJr** [comment]
Olá Tania, 

o erro já foi ajustado. Caso o coordenador precise dar encaminhamento aos projetos, deve-se também atribuir o perfil de secretaria.
