### ISSUE TITLE
Presentacion de enmienda no permite ingresar informacion de fuente de financiamiento ni patrocinador

### ISSUE THREAD

**Issue by trivasf** [bireme/proethos#144]
El sistema da un error en la lista de verificacion y por lo tanto no deja presentar la enmienda.
Ver:
![enmienda_financiamiento y patrocinador](https://cloud.githubusercontent.com/assets/10438244/11200038/90b3d13a-8ca0-11e5-9790-87a1ec9eaddc.jpg)
![enmienda_error](https://cloud.githubusercontent.com/assets/10438244/11200040/94c2319a-8ca0-11e5-9af3-ac1eb6192c82.jpg)

**Comment by moacirmoda** [comment]
Tania,

Buenos dias,

Yo corrigi el error y já pedi para Vinicius actualizar el ambiente de
homologación.

Saludos.

**Comment by trivasf** [comment]
Muchas gracias Moacir!
Feliz dia!

Tania Flores
ProEthos Consultant
Knowledge Management, Bioethics and Research
Pan American Health Organization


ProEthos is an innovative platform for the ethics review of research with human subjects.
Learn more and download here<http://www.paho.org/proethos>.

________________________________

**Comment by trivasf** [comment]
Es posible que el ambiente de homologacion no ha sido actualizado aun, pues el problema persiste.
Esperamos confirmacion de actualizacion para revisar y cerrar issue.

GRacias!

Tania Flores
ProEthos Consultant
Knowledge Management, Bioethics and Research
Pan American Health Organization


ProEthos is an innovative platform for the ethics review of research with human subjects.
Learn more and download here<http://www.paho.org/proethos>.

________________________________
From: Flores, Tania (WDC)
Sent: Tuesday, November 17, 2015 8:58 AM
To: bireme/proethos; bireme/proethos
Subject: RE: [proethos] Presentacion de enmienda no permite ingresar informacion de fuente de financiamiento ni patrocinador (#144)

Muchas gracias Moacir!
Feliz dia!

Tania Flores
ProEthos Consultant
Knowledge Management, Bioethics and Research
Pan American Health Organization


ProEthos is an innovative platform for the ethics review of research with human subjects.
Learn more and download here<http://www.paho.org/proethos>.

________________________________

**Comment by moacirmoda** [comment]
És possible.
Estoy aguardando la respuesta de vinicius.

**Comment by trivasf** [comment]
Resuelto. Gracias!
