### ISSUE TITLE
La ultima actualizacion del sistema ha desconfigurado algunas opciones

### ISSUE THREAD

**Issue by trivasf** [bireme/proethos#147]
Despues de realizar una actualizacion del sistema - Vinicius la realizo por indicacion de Rene el 7 de enero de 2016 - algunas opciones dentro del sistema que estaban funcionando correctamente, ahora no estan funcionando:

No pueden presentarse protocolos nuevos. Ver:
![presentacion protocolo nuevo incompleto](https://cloud.githubusercontent.com/assets/10438244/13086577/d149842a-d4b1-11e5-9418-5a9cb3347510.jpg)

Las acciones de seguimiento no estan funcionando. Ninguna. Ver:
![acciones de seguimiento no funcionan](https://cloud.githubusercontent.com/assets/10438244/13086711/63b86484-d4b2-11e5-9748-9dcb66249165.jpg)

Los acentos en espanol de los mensajes de correo electronicos desde el sistema, otra vez no funcionan. Ver:
![acentos en espanol no funcionan](https://cloud.githubusercontent.com/assets/10438244/13086763/9ba67f16-d4b2-11e5-8b8d-1a9d269f4374.jpg)

Necesitamos corregir estos errores. Retroceder al sistema de antes del 7 de enero de 2016.

**Comment by wilsonmoura** [comment]
Depricated version of ProEthos. New version available at https://github.com/bireme/proethos2
