### ISSUE TITLE
Los documentos nuevos que se adjuntan a protocolos reenviados no los recibe el comite.

### ISSUE THREAD

**Issue by trivasf** [bireme/proethos#148]
El investigador adjunta nuevos documentos en un protocolo rechazado para reenviar. Ver:
![docs nuevos en protocolo reenviado](https://cloud.githubusercontent.com/assets/10438244/13289887/959dac1a-dadf-11e5-9170-1c2d96fc96d4.jpg)

El comite al recibir el protocolo reenviado, no recibe los documentos nuevos. Ver:
![docs nuevos en protocolo reenviado_no visibles para comite](https://cloud.githubusercontent.com/assets/10438244/13289958/dc5cb93e-dadf-11e5-8467-fb409c4d02d4.jpg)

**Comment by wilsonmoura** [comment]
Depricated version of ProEthos. New version available at https://github.com/bireme/proethos2
