### ISSUE TITLE
Delay in system emails?

### ISSUE THREAD

**Issue by trivasf** [bireme/proethos#149]
After tests with external parties, they have detected that when asking for "forgotten password", the system didn't emailed them the password information, until 2 days after they requested it, but the system says the email was sent 1 day before they requested...
So, user requested password information on a Tuesday. System emailed password information on the Thursday of the same week. But email says it was sent on Monday of the same week.

**Comment by renatomurasaki** [comment]
What is the ProEthos instance with this problem?

Renato

**Comment by trivasf** [comment]
User requested password on Tuesday March 8th, 2016.
She received the following message today, Thursday March 10th, 2016.
Please note date on email: Monday, March 07, 2016

From: Comité de Ética de la OPS [mailto:proethos@pombo.bireme.br]
Sent: Monday, March 07, 2016 1:28 PM
To: Ghimenti, Ms. Katherine (WDC)
Subject: Forgotten password information

Dear Investigator, As requested, an email has been sent to you with your password information. Regards, best wishes! Ethics Committee

MSG_COD:send_email_text

Password: PAHO1234


System is not responding in a timely manner.

Tania Flores
ProEthos Consultant
Knowledge Management, Bioethics and Research
Pan American Health Organization


ProEthos is an innovative platform for the ethics review of research with human subjects.
Learn more and download here<http://www.paho.org/proethos>.

________________________________

**Comment by renatomurasaki** [comment]
Tania, this problem is not related to ProEthos platform. It is an email service issue connected to the ProEthos homolog environment. Please, closed the issue.

Renato

**Comment by trivasf** [comment]
Closing issue as per Renato's request
