### ISSUE TITLE
Request to Carla Saenz the documents of the methodology

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/proethos#15]
The followinbg documents available on

http://proethos.teste.bvsalud.org/documents.php

- Guía para la revisión ética
- Modelo de reporte de evento adverso

Modelo de dictamen
- Aprobación
- Aprobación condicionalproethos_doc_diac
- No aprobación/

**Comment by carlasaenz** [comment]
He revisado los documentos que envié según una revisión de terminología que hicimos en el sistema (usando solo el término protocolo, no propuesta o proyecto), así que les envío los documentos revisados. 
En general, los documentos tienen tres categorías:
1. Guías para la revisión ética
2. Seguimiento a protocolos aprobados
3. Decisiones del Comité
Sin embargo, el # 3 solo debe estar disponible para el Comité (admin, secretaria, miembros) mas no debe ser visible con el perfil de los investigadores.
Voy a enviar por email todos los documentos revisados poniendo cada categoría en el subject line.
Además, debe ser posible para los admin subir nuevos documentos; por ejemplo los comités pueden querer agregar otros documentos, como la ley y regulación nacional u otros formatos que usen.

**Comment by renatomurasaki** [comment]
Los documentos "aproación enmienda", "aprobación extension", "aprobado", "condicionalmente aprobado", "exento", "no aprobado" solo deben ser accesibles para el admin, secretaria y acaso miembros del comité:

Aprobado 
Approved 

Condicionalmente aprobado
Conditionally approved

No aprobado
Not approved

Exento
Exempt

Enmienda aprobada
Approved amendment

Extensión aprobada
Approved extension

(definiciones enviadas por Carla Saenz por correo en 22/01/15 - "ProEthos issue 15 - Documentos para cargar en Plantillas de documentos bajo "Decisiones"")

**Comment by renatomurasaki** [comment]
Los documentos "Reporte de EVENTOS ADVERSOS", "Solicitud de ENMIENDA", "Solicitud de EXTENSION DE APROBACION" van bajo "seguimiento":

Reporte de eventos adversos [Esp]
Adverse events report [Eng]

Enmienda a protocolo aprobado [Esp]
Amendment to approved protocol [Eng]

Extensión a la aprobación [Esp]
Extension of approval [Eng]

(definiciones enviadas por Carla Saenz por correo en 22/01/15 - "ProEthos issue 15 - Documentos para cargar en Plantillas de documentos bajo "Seguimiento a protocolos aprobados")

**Comment by carlasaenz** [comment]
No veo la actualización. AL hacer clic en los documentos da error. En la caja de Modelos de documentos además dice: 
Warning: array_push() expects parameter 1 to be array, null given in /home/apps/bvsalud.org/proethos/htdocs/documents_proethos.php on line 4
Y los subtítulos de las secciones y nombres de los documentos no coinciden con lo que dice acá en el issue.

**Comment by carlasaenz** [comment]
Los subtítulos de las secciones y nombres de los documentos todavía no coinciden con lo que dice acá en el issue, a pesar de que se corrigió el mensaje de error de arriba. No todos los subtítulos ni nobmres de documentos se pueden cambiar, solo algunos y arbitrariamente, y los nombres incluidos no se entienden:
![image](https://cloud.githubusercontent.com/assets/10438060/5943212/0656e536-a6eb-11e4-8654-063f1df0aacb.png)
