### ISSUE TITLE
No se muestra la imagen del código captcha al crear un nuevo usuario

### ISSUE THREAD

**Issue by MariaCorrea** [bireme/proethos#150]
Buen día.

Al intentar crear un nuevo usuario desde la interfaz pública, no se muestra la imagen del código captcha por lo cual el proceso no puede ser finalizado. Adjunto imagen.

Quedo atenta a sus oportunos comentarios.

Gracias!.

![screenhunter_206 apr 21 15 36](https://cloud.githubusercontent.com/assets/17206862/14723523/1bb32680-07d7-11e6-861f-9406c16f7d45.jpg)

**Comment by ovidiopadilla** [comment]
Buen Día.

Actualizando el navegador y los complementos de flash y java se soluciona.

Saludos



Enviado con MailTrack
<https://mailtrack.io/install?source=signature&lang=es&referral=ovidiopadilla@gmail.com&idSignature=23>
ᐧ

2016-04-21 14:19 GMT-06:00 MariaCorrea <notifications@github.com>:

> Buen día.
>
> Al intentar crear un nuevo usuario desde la interfaz pública, no se
> muestra la imagen del código captcha por lo cual el proceso no puede ser
> finalizado.
>
> Quedo atenta a sus oportunos comentarios.
>
> Gracias!.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bireme/proethos/issues/150>
>



-- 
Ovidio Enrique Padilla García
Coordinador Tecnologías de Información
Biblioteca Médica Nacional, Facultad de Ciencias Médicas UNAH
Bibliotecas Virtuales en Salud Honduras, Plataforma Proethos
Observatorio de Recursos Humanos en Salud Honduras
Centro de Información Sobre Desastres Biblioteca Médica Nacional
Red Latinoamericana de Centros de Información en Gestión del Riesgo,
Desastres y Salud
Móvil: 504-33921384,99190266 Oficina: 504-22325804

**Comment by MariaCorrea** [comment]
Buen día Ovidio.

Seguí los pasos indicados y el problema persiste. ¿Qué más me recomiendas realizar?. Estoy trabajando con la siguiente configuración:

Firefox 45.0.2.
Java SE 8 U91
Adobe Flash Player Version 21.0.0.213.

Estaré atenta a cualquier comentario.

Gracias!.

**Comment by ovidiopadilla** [comment]
Verifiquen la siguiente lista de cotejo:

Firefox no muestra las imágenes o animaciones

Si experimentas problemas para descargar o visualizar imágenes en Firefox,
sigue las instrucciones sobre la resolución de problemas que se explican a
continuación.

Este artículo es válido para:

   - Imágenes con formato PNG, GIF y JPG.
   - Archivos de animación en formato GIF animado.

Este artículo no es válido para:

   - Los formatos de vídeo, como MPG, WMV, y AVI. Para obtener más
   información, puedes ver el artículo Solucionar problemas comunes de
   audio y video
   <https://support.mozilla.org/es/kb/solucionar-problemas-comunes-de-audio-y-video>
   .
   - Contenido animado que se muestra a través de un plugin, como por
   ejemplo el plugin de Adobe Flash. Para obtener más información, puedes ver
   el artículo Plugin de Flash: mantenlo actualizado y soluciona muchos
   problemas
   <https://support.mozilla.org/es/kb/plugin-de-flash-mantenlo-actualizado-y-soluciona-problemas>
   .

*Nota:* Si ves el icono [image: Mixed Content Shield] en la barra de
herramientas y tienes problemas para ver esa página web, consulta el
artículo ¿Cómo afecta a mi seguridad el contenido no seguro?
<https://support.mozilla.org/es/kb/como-afecta-mi-seguridad-el-contenido-no-seguro>
.

Tabla de contenidos

   - Eliminar las cookies y la caché
   <https://support.mozilla.org/es/kb/firefox-no-muestra-las-imagenes-o-animaciones#w_eliminar-las-cookies-y-la-cachae>
   - Comprueba los permisos de las imágenes de una determinada página web
   <https://support.mozilla.org/es/kb/firefox-no-muestra-las-imagenes-o-animaciones#w_comprueba-los-permisos-de-las-imaagenes-de-una-determinada-paagina-web>
   - Software de seguridad
   <https://support.mozilla.org/es/kb/firefox-no-muestra-las-imagenes-o-animaciones#w_software-de-seguridad>
   - Las imágenes se cargan la primera vez, pero no las veces posteriores
   <https://support.mozilla.org/es/kb/firefox-no-muestra-las-imagenes-o-animaciones#w_las-imaagenes-se-cargan-la-primera-vez-pero-no-las-veces-posteriores>
   - Las imágenes cargan pero se ven mal
   <https://support.mozilla.org/es/kb/firefox-no-muestra-las-imagenes-o-animaciones#w_las-imaagenes-cargan-pero-se-ven-mal>
   - Otras razones por que puede que las imágenes no cargan
   <https://support.mozilla.org/es/kb/firefox-no-muestra-las-imagenes-o-animaciones#w_otras-razones-por-que-puede-que-las-imaagenes-no-cargan>
   - Las imágenes o animaciones todavía no se cargan correctamente
   <https://support.mozilla.org/es/kb/firefox-no-muestra-las-imagenes-o-animaciones#w_las-imaagenes-o-animaciones-todavaga-no-se-cargan-correctamente>

Eliminar las cookies y la caché

A veces, los problemas que surgen al cargar las páginas web se pueden
solucionar limpiando las cookies y la caché.

   1. Haz clic en el botón Menú [image: New Fx Menu] , elige Historial y
   selecciona Limpiar el historial reciente....
   2. En el menú desplegable *Rango temporal a limpiar:* selecciona *Todo*.
   3. Haz clic en la flecha al lado de *Detalles* para mostrar la lista de
   elementos que se borrarán.
   4. Selecciona *Cookies* y *Caché*.
   5. Haz clic en Limpiar ahora.

Comprueba los permisos de las imágenes de una determinada página web

Firefox te permite evitar que se carguen las imágenes de determinados
sitios web para que las páginas se carguen más rápido. Si tienes problemas
para ver las imágenes, sigue los pasos que se indican a continuación:

   1. Haz clic en el botón de identidad de la página web
   <https://support.mozilla.org/es/kb/boton-de-identidad-de-sitio> (el
   icono que aparece a la izquierda de su dirección).
   2. Haz clic en Más información…. Se abrirá la ventana de información de
   la página
   <https://support.mozilla.org/es/kb/Informaci%C3%B3n-de-la-p%C3%A1gina>.
   3. Selecciona el Panel Permisos.
   4. Asegúrate de que la casilla *Permitir*, al lado de *Cargar imágenes* está
   seleccionada.
   5. Cierra la página de información.

Software de seguridad

Determinados problemas para la seguridad en Internet (esto incluye los
antivirus, el software anti-spyware, firewall, programas de privacidad y
otros) pueden identificar y bloquear ciertas imágenes, como web bugs o
pueden evitar que se carguen las imágenes de la animación. Comprueba la
configuración de tu programa de seguridad en Internet para asegurarte de
que permite que las imágenes se carguen.
Las imágenes se cargan la primera vez, pero no las veces posteriores

El complemento RealPlayer Browser Record Plugin (que se instala con
RealPlayer) puede hacer que Firefox muestre las imágenes correctamente en
la primera visita a un sitio web, pero no en las subsiguientes visitas o
actualizaciones. Si deshabilitas esta extensión se solucionará el problema.

   1. Abre el programa RealPlayer.
   2. Dirígete al menú Herramientas y haz clic en el menú Preferencias.
   3. Dirígete a la sección Descargar y Grabar y desmarca la casilla de
   verificación *Habilitar la descarga web y grabación para estos
   navegadores instalados*.
   4. Haz clic en el botón Aceptar.

O puedes ver el artículo Resolución de incidencias relacionadas con
extensiones, temas y aceleración de hardware para solucionar problemas
comunes de Firefox
<https://support.mozilla.org/es/kb/resolucion-de-incidencias-relacionadas-con-extensi>
para
obtener más información sobre cómo deshabilitar o desinstalar complementos
en Firefox.
Las imágenes cargan pero se ven mal

Si las imágenes de los sitios web, se cargan pero no se ven bien o no se
muestran igual que en otros navegadores:

   - Si estás usando algún tipo de software acelerador de carga de páginas
   web, desactívalo y comprueba si las imágenes se cargan correctamente. Para
   obtener más información, consulta la documentación que se incluye con el
   software.
   - Si la imagen muestra el texto o algún tipo de galimatías, consulta el
   artículo de la Base de conocimiento de MozillaZine, La página se muestra
   como un galimatías <http://kb.mozillazine.org/Page_displays_as_gibberish>

Otras razones por que puede que las imágenes no cargan

   - El sitio web que muestra las imágenes está inactivo o está sufriendo
   algún tipo de problema. Para verificarlo, intenta cargar el sitio web desde
   un ordenador o navegador diferente.
   - Algunas rutas de acceso a las imágenes contienen barras invertidas
   (por ejemploexample.com\MyImage.jpg). En navegadores distintos a
   Internet Explorer, esas rutas de acceso a las imágenes no cargan. Si ves
   una URL de una imagen que contenga una barra invertida, ponte en contacto
   con el administrador del sitio web para informar sobre este problema.


   - Puede que hayas modificado uno de los ajustes de Firefox y eso
   provoque que no se vean las imágenes. Puedes o bien restablecer las
   preferencias
   <https://support.mozilla.org/es/kb/Restablecer%20las%20preferencias> o
   intentar una de estas soluciones:


   1.

   En la barra de direcciones
   <https://support.mozilla.org/es/kb/buscar-en-tus-marcadores-historial-y-pestanas-con-barra-alucinante>,
   escribe *about:config* y pulsa Intro.
   - El aviso de about:config *"¡Zona hostil para manazas!"* o *"¡Esto
      puede cancelar su garantía!"*puede aparecer. Haz clic en ¡Tendré
      cuidado, lo prometo! o¡Seré cuidadoso, lo prometo!, para continuar.
   2. En la lista de preferencias, busca la opción
   *browser.display.use_document_colors*. Por defecto, debería aparecer
   como *true*.
   3. Si el valor que aparece es *false*, Haz clic con el botón secundario en
   la preferencia y selecciona Restablecer.

Las imágenes o animaciones todavía no se cargan correctamente

Si has intentado todas las soluciones que se indican en este artículo y las
imágenes o animaciones todavía no se cargan correctamente, intenta una de
estas soluciones:

   - Intenta restablecer las opciones por defecto de Firefox
   <https://support.mozilla.org/es/kb/restablecer-firefox-una-forma-facil-de-solucionar->
   .
   - Use the Profile Manager to create a new Firefox profile
   <https://support.mozilla.org/es/kb/usar-el-administrador-de-perfiles-para-crear-y-eli>
   .
   - Sigue los pasos que se indican en el artículo Resolución y diagnóstico
   de problemas con Firefox
   <https://support.mozilla.org/es/kb/resolucion-y-diagnostico-de-problemas-con-firefox>
   .



*Basado en información extraída del artículo Las imágenes o animaciones no
cargan (mozillaZine KB)
<http://kb.mozillazine.org/Images_or_animations_do_not_load>*



Enviado con MailTrack
<https://mailtrack.io/install?source=signature&lang=es&referral=ovidiopadilla@gmail.com&idSignature=23>
ᐧ

El 21 de abril de 2016, 15:48, MariaCorrea <notifications@github.com>
escribió:

> Buen día Ovidio.
>
> Seguí los pasos indicados y el problema persiste. ¿Qué más me recomiendas
> realizar?. Estoy trabajando con la siguiente configuración:
>
> Firefox 45.0.2.
> Java SE 8 U91
> Adobe Flash Player Version 21.0.0.213.
>
> Estaré atenta a cualquier comentario.
>
> Gracias!.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/bireme/proethos/issues/150#issuecomment-213126678>
>



-- 
Ovidio Enrique Padilla García
Coordinador Tecnologías de Información
Biblioteca Médica Nacional, Facultad de Ciencias Médicas UNAH
Bibliotecas Virtuales en Salud Honduras, Plataforma Proethos
Observatorio de Recursos Humanos en Salud Honduras
Centro de Información Sobre Desastres Biblioteca Médica Nacional
Red Latinoamericana de Centros de Información en Gestión del Riesgo,
Desastres y Salud
Móvil: 504-33921384,99190266 Oficina: 504-22325804

**Comment by MariaCorrea** [comment]
Buen día Ovidio.

Se intentó todo lo relacionado en la guía con la no carga de las imágenes y el problema aún persiste. Incluso, se intentó probando en otros navegadores desde diferentes sistemas operativos y no se muestra un resultado positivo. ¿Alguna recomendación adicional?.

Estaré atenta a cualquier novedad.

Gracias por la colaboración.

**Comment by ovidiopadilla** [comment]
Buen día.
La siguiente prueba seria verificar la versión instalada de Proethos y
actualizar a la última versión si es posible.
Me pueden enviar el enlace de su plataforma para verificar.
Saludos

**Comment by MariaCorrea** [comment]
Cordial saludo,

Se refiere a este enlace?

http://172.30.200.13/proethos/login.php

Gracias por su valiosa colaboración.



Enviado con MailTrack
<https://mailtrack.io/install?source=signature&lang=es&referral=cbioeticasiu@udea.edu.co&idSignature=23>

El 29 de abril de 2016, 17:43, ovidiopadilla <notifications@github.com>
escribió:

> Buen día.
> La siguiente prueba seria verificar la versión instalada de Proethos y
> actualizar a la última versión si es posible.
> Me pueden enviar el enlace de su plataforma para verificar.
> Saludos
> El abr. 26, 2016 4:29 PM, "MariaCorrea" <notifications@github.com>
> escribió:
>
> > Buen día Ovidio.
> >
> > Se intentó todo lo relacionado en la guía con la no carga de las imágenes
> > y el problema aún persiste. Incluso, se intentó probando en otros
> > navegadores desde diferentes sistemas operativos y no se muestra un
> > resultado positivo. ¿Alguna recomendación adicional?.
> >
> > Estaré atenta a cualquier novedad.
> >
> > Gracias por la colaboración.
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/bireme/proethos/issues/150#issuecomment-214907125>
>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bireme/proethos/issues/150#issuecomment-215900536>
>



-- 


*María C. Correa*

*Comité de Bioética para investigación en Humanos*

*Sede de Investigación Universitaria*

*Carrera 53 # 61-30*

*cbioeticasiu@udea.edu.co <comitebioetica@siu.udea.edu.co>*

*Teléfono: +57 (4) 2196612*


*Medellín-Colombia*


[image: SIU]
<http://www.udea.edu.co/portal/page/portal/Programas/GruposInvestigacion/sedeInvestigacionUniversitaria>[image:
ICONTEC] <http://www.icontec.org/index.php/es/>
[image: PQRSFD] <http://siuweb.udea.edu.co:8080/pqrs>
[image: FACEBOOK]
<https://www.facebook.com/pages/Sede-de-Investigaci%C3%B3n-Universitaria-SIU/141663186632?ref=hl>[image:
TWITTER] <https://twitter.com/SIUUdeA>



*Sus peticiones, quejas, reclamos, sugerencias, denuncias o
felicitaciones pueden ser expresados ingresando al siguiente enlace: *
*Sistema de Gestión de PQRSD
<http://siuweb.udea.edu.co:8080/pqrs/principal.jsp?txtCedula=null&preload=null>*

-- 


*Universidad de Antioquia*
www.udea.edu.co
Sede Principal: Calle 67 # 53 -108
Medellín, Colombia 


"La información aquí contenida es para uso exclusivo de la persona o 
entidad de destino. Está estrictamente prohibida su utilización, copia, 
descarga, distribución, modificación y/o reproducción total o parcial, sin 
el permiso expreso de Universidad de Antioquia, pues su contenido puede ser 
de carácter confidencial y/o contener material privilegiado. Si usted 
recibió esta información por error, por favor contacte en forma inmediata a 
quien la envió y borre este material de su computador. Universidad de 
Antioquia no es responsable por la información contenida en esta 
comunicación, el directo responsable es quien la firma o el autor de la 
misma."

**Comment by wilsonmoura** [comment]
Depricated version of ProEthos. New version available at https://github.com/bireme/proethos2
