### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HeHeRiBo** [bireme/proethos#153]
Buenas.

En toda la plataforma me aparece el siguiente mensaje:
Warning: A non-numeric value encountered in /var/www/html/proethos2/cab.php on line 84

Además cuando quiero agregar preguntas frecuentes, en la opción idioma, la primera alternativa es:
option value="pt_BR">Portugues

La instalación esta en un Servidor con:
Ubuntu 18.04.4 - Php 7.2.24 - MySQL 5.7.28

**Comment by wilsonmoura** [comment]
Depricated version of ProEthos. New version available at https://github.com/bireme/proethos2
