### ISSUE TITLE
Update responsibility and terms of use documents

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/proethos#16]
Awaiting legal discussions about the license to update the documents related to responsibility and terms of use.

**Comment by carlasaenz** [comment]
FYI, la Oficina Legal ha contactado a GitHub y solicitado para para OPS, como Organización internacional, las mismas excepciones que GitHub le hace ya al gobierno de los EEUU. Mientras tanto están revisando los documentos legales y tienen una consulta específica que te haré por email en función a la cual tendrán en texto adaptado manhana.

**Comment by wilsonmoura** [comment]
Depricated version of ProEthos. New version available at https://github.com/bireme/proethos2
