### ISSUE TITLE
Modify files with copyrights to PAHO/WHO

### ISSUE THREAD

**Issue by ReneFGJr** [bireme/proethos#32]
@copyright Copyright (c) 2015 -  Pan-American Health Organization / World Health Organization (PAHO/WHO)

**Comment by carlasaenz** [comment]
El copyright de ProEthos es del 2013. Debería decir siempre:
© Pan American Health Organization, 2013. All rights reserved.

**Comment by carlasaenz** [comment]
Este issue aparece coomo cerrado pero el problema persiste, en la página de entrada y en las otras: 
![image](https://cloud.githubusercontent.com/assets/10438060/5861544/5009d344-a238-11e4-9176-28f2b0fc470b.png)

**Comment by renatomurasaki** [comment]
Todavia no está reflejado en el ambiente de homologación porque no fue sincronizado el sistema con las ultimas actualizaciones. Haremos eso mañana.

Renato

**Comment by carlasaenz** [comment]
Ah, ok. Gracias por la aclaración!

Carla Saenz, PhD
Bioethics Regional Advisor
Knowledge Management, Bioethics and Research
Pan American Health Organization

**Comment by renatomurasaki** [comment]
Despues de la actualización, todavia el pie de pagina tiene problemas para mostrar la formatación del copyright.

**Comment by ReneFGJr** [comment]
O copyright ficou para ser parametrizado.

**Comment by carlasaenz** [comment]
Una aclaración: esto no significa que cada uno puede cambiar esto fácilmente, verdad?
Además, luego de "All rights reserved" hay unos signos que hay que borrar:
© Pan American Health Organization, 2013. All rights reserved.xxx ?>

**Comment by trivasf** [comment]
Gracias!

Please pardon any typos. Sent from my iPhone.
