### ISSUE TITLE
Al hacer el tamizaje de una propuesta, el admin deberia tener la opcion de “aceptar la propuesta para evaluacion etica”

### ISSUE THREAD

**Issue by ReneFGJr** [bireme/proethos#35]
Após a exibição de uma proposta, o administrador deve ter a opção de "aceitar a proposta para a avaliação ética" ou enviado aos membros da comissão para eles entrarem seus votos e decidir se a proposta ou não requerem revisão ética. No momento, não está claro como isso seria feito. Se o login admin "decidir sobre os membros proposta", a tela vai diretamente para os membros votam, mas não permite que o administrador enviar a proposta aos membros para dizer-lhes para votar.
O domínio do género na proposta apenas dá a opção de homens, mulheres ou ambos. Sem opção para menores. O sistema aceita que inserir amostra com idade as crianças.

**Comment by carlasaenz** [comment]
René, con respecto a la participación de menores, adicionalmente se podría incluir una casilla que diga: Menores, y permita que uno marque: si  - no ?
Con respecto al tamizaje de la propuesta, el admin debe ser capaz de (a) decidir por sí mismo si la propuesta necesita revisión ética o no, o (b) consultar a los miembros del comité para tomar la decisión de manera conjunta. Para (b) sería bueno si (i) el admin puede mandar un email desde el sistema a todos los miembros haciendo la consulta y (ii) si los miembros pueden visibilizar la propuesta en el sistema luego de recibir este email y luego poner sus comentarios en las casillas ya disponibles para las comunicaciones internas. 
Finalmente, si se decide que la propuesta no necesita revisión ética (por la vía (a) o por la vía (b)) entonces se tiene que poder emitir la decisión oficial ('exento') desde el sistema. Esta pasa a ser una propuesta con decisión. 
Para esta y para todas las decisiones el admin debe poder subir (upload) al sistema el dictamen con las firmas y comunicar a los investigadores desde el sistema que ya hay una decisión.

**Comment by trivasf** [comment]
El admin SI tiene la opcion de aceptar la propuesta para evaluacion. Lo que no esta claro, es que el admin pueda enviar la propuesta a los miembros del comite para decider si una propuesta necesita evaluacion etica. Al hacer click en "Aceptar protocol para evaluacion", da ambas ocpiones. Ver adjunto. Pero si el admin hace click en "El comite decide si require revision etica", no da la opcion de enviarlo a los miembros. La pantalla se muestra como para miembro, para votar por la decision. Ver adjunto.
![decision admin](https://cloud.githubusercontent.com/assets/10438244/5859702/25ec13f0-a211-11e4-8623-d8c97f7959d6.jpg)
![decision miembro](https://cloud.githubusercontent.com/assets/10438244/5859703/2600ea64-a211-11e4-8460-ee55ba58bcf5.jpg)

**Comment by trivasf** [comment]
El admin si puede decidir pero el miembro del comite no. Se necesita agregar el boton de decision para las opiniones de miembro.

**Comment by trivasf** [comment]
Solucionado. Cerramos issue.
