### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/proethos#4]

**Comment by renatomurasaki** [comment]
KBR team is working on the translation using the features Menu Del Administrador > Menu Especial del Administrador > Mensajes del sistema.

**Comment by renatomurasaki** [comment]
Este es un proceso continuado de trabajo, teniendo en cuenta la creación de nuevos campos y etiquetas que necesitan ser traducidos. El flujo de traducción via sistema está funcionando correctamente, lo que nos permite cerrar el issue:

Menu Del Administrador > Menu Especial del Administrador > Mensajes del sistema
Menu Del Administrador > Menu Especial del Administrador > Actualizar mensajes del sistema
