### ISSUE TITLE
Puede “autollenarse” el ID de la propuesta y la fecha?

### ISSUE THREAD

**Issue by ReneFGJr** [bireme/proethos#40]
Você pode "autollenarse" o ID da proposta e da data?

**Comment by ReneFGJr** [comment]
o   Todos salen de “root user” –Se puede cambiar? Es el “sender” parametrizable? Y si no lo es, podemos cambiarlo?

o   Puede “autollenarse” el ID de la propuesta y la fecha?

**Comment by trivasf** [comment]
Tania va a crear estos campos automaticos en los emails. Esto esta ligado al issue #129

**Comment by wilsonmoura** [comment]
Depricated version of ProEthos. New version available at https://github.com/bireme/proethos2
