### ISSUE TITLE
Comunicaciones entre el sistema y el investigador no funciona

### ISSUE THREAD

**Issue by trivasf** [bireme/proethos#46]
El Sistema comunica la decision al investigador, pero cuando el investigador trata de responder al correo recibido, el correo es devuelto como error. El Sistema no registra las comunicaciones del investigador. Ver screenshot
![communications screeshot](https://cloud.githubusercontent.com/assets/10438244/5848875/6b0546a2-a192-11e4-8284-81b18473ab8a.jpg)

**Comment by viniciusandrade** [comment]
@trivasf 

Favor hacer nueva prueba.

**Comment by carlasaenz** [comment]
El sistema envía el email a los investigadores, pero si los investigadores hacen reply a ese email reciben un "failure notice". Es posible que esto sea porque el email sale del admin, y en ese y en el caso de los otros perfiles creados por Rene (adhoc, investigador, membro, secretaria, admin, coordenador) no hay un email asignado? (A diferencia por ejemplo del usuario Carla Yahoo Saenz (csaenzb@yahoo.com) y del usuario saenzcar@paho.org (que no sé claramente qué perfil tiene).

**Comment by trivasf** [comment]
El Sistema continua enviando emails al investigador pero el investigador no puede responder.

**Comment by trivasf** [comment]
Al momento, los perfiles del Sistema no estan amarrados a ninguna direccion de correo electronico. Entonces el investigador al tartar de responder a un email recibido del Sistema, no puede responder. Esto se arreglaria al momento de que cada comite baje el software y configure sus perfiles con un email?

**Comment by renatomurasaki** [comment]
Probamos el envio cambiando el correo de reply en la configuración de los datos del comite con el e-mail de Tania y fue posible hacer el reply.
