### ISSUE TITLE
Comentarios ProEthos

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/proethos#47]
1.	El Sistema permite presenter la propuesta sin nombre de investigador.
2.	Cuando el admin acepta la propuesta para revision, o los miembros votan para aceptarla o no, el Sistema no guarda esta informacion bajo historial. Ver:
![comentario-proethos-1](https://cloud.githubusercontent.com/assets/1226218/5855163/2d4e4892-a21c-11e4-991d-da7095cfab75.png) 
3. El Sistema me permite realizer el proceso de revision e incluso tomar decision sobre la propuesta y comunicarla al investigador, pero no hay investigador. No se adonde va la comunicacion porque el Sistema la acepta y la senhala como “investigacion en curso”.
4.  La decision de la propuesta “Propuesta de investigacion" fue “Condicionalmente aprobada", sin embargo el Sistema la muestra como "aprobada" solamente. 
5.  Asigne dos revisores para esta propuesta, pero si quiero cambiar alguno de los asignados (como sucede en casos en los que los invitados a revisar rechazan la invitacion), el Sistema no me deja cambiar a los asignados originalmente. 
6.  El PDF que el Sistema crea de una propuesta, muestra algunos campos que no estan originalmente en la propuesta. Ver "descripcion de la actividad”:
![comentario-proethos-2](https://cloud.githubusercontent.com/assets/1226218/5855179/58186e04-a21c-11e4-95dd-e89211aba0d5.png)

**Comment by trivasf** [comment]
Estoy cerrando este issue, y abriendo los  que quedan pendientes de resolver (3 ultimos - 4,5,6) como nuevos independientes.
