### ISSUE TITLE
Check deployment process in order to avoid burning exist translations

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/proethos#48]

**Comment by viniciusandrade** [comment]
Segundo informado pelo @ReneFGJ as traduções são armazenadas no banco de dados e gravadas em arquivos do filesystem abaixo do diretório messages/ ao se utilizar a opção "Actualizar mensajes del sistema"  disponível no perfil de administrador.

**Comment by trivasf** [comment]
Estimados

Despues de revisar las traducciones y verificar que aun no son visibles en el Sistema, hice click en “actualizar mensajes del Sistema”, pero esto es lo que recibi y despues de volver a verificar, las traducciones siguen sin reflejarse

 






From: viniciusandrade
Sent: ‎Friday‎, ‎January‎ ‎23‎, ‎2015 ‎3‎:‎21‎ ‎AM
To: bireme/proethos





Segundo informado pelo @ReneFGJ as traduções são armazenadas no banco de dados e gravadas em arquivos do filesystem abaixo do diretório messages/ ao se utilizar a opção "Actualizar mensajes del sistema" disponível no perfil de administrador.

**Comment by viniciusandrade** [comment]
@trivasf,

El problema estaba en los permisos de la carpeta de mensajes en nuestro servidor. Hemos revisado y ahora debe estar OK.

Atentamente.

**Comment by trivasf** [comment]
Esto esta ya funcionando bien.

Gracias!








From: viniciusandrade
Sent: ‎Thursday‎, ‎January‎ ‎29‎, ‎2015 ‎3‎:‎23‎ ‎AM
To: bireme/proethos
Cc: Tania Flores





@trivasf,

El problema estaba en los permisos de la carpeta de mensajes en nuestro servidor. Hemos revisado y ahora debe estar OK.

Atentamente.
