### ISSUE TITLE
No se pueden ver los protocolos aprobados

### ISSUE THREAD

**Issue by carlasaenz** [bireme/proethos#49]
Al hacer clic en bajo protocolo aprobado, sea por el número de identificación o donde dice "preopuesta de investigación" en esta pantalla (copiada) me sale el mensaje de error de abajo 
![image](https://cloud.githubusercontent.com/assets/10438060/5858380/be3bebee-a220-11e4-8f3f-9e82306a7847.png)

![image](https://cloud.githubusercontent.com/assets/10438060/5858321/318602d4-a220-11e4-98ec-3be4ae06134b.png)

**Comment by trivasf** [comment]
El investigador no puede ver las propuestas con decision aun. El Sistema da error.

**Comment by ReneFGJr** [comment]
Check Please!

**Comment by carlasaenz** [comment]
Sigo sin poder verlos. Si hago clic en el título o en el ID el sistema me manda a esta página http://proethos.homolog.bvsalud.org/protocol_detalhe_investigator.php?dd0=6&dd90=91c5a880fa con un mensaje de "Not Found"

Carla Saenz, PhD
Regional Bioethics Advisor
Department of Knowledge Management, Bioethics and Research
Pan American Health Organization
________________________________

**Comment by carlasaenz** [comment]
Ahora con la actualización que hizo Vinicius salen ya, pero tenemos todavía dos problemas:
1. Lo que aparece como dictamen (con el título de Local ethical approval) NO es el dictamen. Ese documento que se llena en el sistema es un documento interno para el Comité que puede tener información que el comité no quiera compartir con los investigadores. El dictamen oficial tiene que tener las firmas, y debe ser hecho usando este documento interno como referencia. Para que se pueda incluir un documento con firmas debe ser posible hacer un upload de un documento en PDF y marcarlo como el dictamen que el investigador debe poder leer.
2. El documento de word (que subí bajo "other") sigue presentando errores de formato, asi que al hacer el download se abre una ventanilla de "convert file" con un menú de opciones, pero no logro que ninguna funcione. Igual para abrir un doc de word no debería necesitarse escoger las opciones, verdad?

Además veo que ya están las opciones de monitoreo, pero escribiré los comentarios correspondientes en el issue de monitoreo. Gracias!


Carla Saenz, PhD
Regional Bioethics Advisor
Department of Knowledge Management, Bioethics and Research
Pan American Health Organization
________________________________

**Comment by viniciusandrade** [comment]
@carlasaenz 

Como el problema original deste issue fue resuelto lo estamos cerrando.

En su ultimo comentario el punto 2 ya esta descrito en el issue #61, ademas hemos revisado los demas issues pero no estamos seguros si el punto 1 ya esta registrado. Podrias confirmar o crear un nuevo issue para este problema?

Gracias.

**Comment by carlasaenz** [comment]
Gracias Vinicius! Abro un nuevo issue con el tema de los dictámenes.

Carla Saenz, PhD
Regional Bioethics Advisor
Department of Knowledge Management, Bioethics and Research
Pan American Health Organization
________________________________
