### ISSUE TITLE
Logos de OPS/OMS están en inglés en página de entrada en espanhol

### ISSUE THREAD

**Issue by carlasaenz** [bireme/proethos#50]
Sería además bueno hacer el logo de ProEthos un poco más visible en la página de entrada (está un poco arrinconado y chico)
![image](https://cloud.githubusercontent.com/assets/10438060/5859547/0edcf306-a229-11e4-911f-361e8de2a255.png)

**Comment by trivasf** [comment]
Hola Rene, yo sigo viendo los logos en ingles. Aparte, hay tres campos en ingles en la pagina en espanhol: "connect with" "or" y "submit". Mira aca:
![proethos home page](https://cloud.githubusercontent.com/assets/10438244/5861520/eccdf8be-a21e-11e4-88cd-65279913de45.jpg)
