### ISSUE TITLE
Seguimiento de propuestas aprobadas: acciones que debe incluir

### ISSUE THREAD

**Issue by carlasaenz** [bireme/proethos#52]
Para cada propuesta que ha sido ya aprobada el investigador debe ver las siguientes seis opciones (hablamos de 7 pero una es parte de la otra). que discutimos la vez pasada. Los tres primeros puntos implican un modelo de documento que los investigadores deben poder subir, y luego un impacto en el flujo porque el comité debe poder emitir una decisión (en caso #1 y #2) que puede ser de aprobación o de no aprobación, y en el caso #3 debe poder enviar una comunicación del comité. 

1.	Solicitud de extensión a la aprobación del protocolo
      (Los investigadores deben subir como pdf un formato que estará bajo plantillas / seguimiento. El comité debe luego poder emitir una decisión y enviar el dictamen respectivo)
2.	Enmienda al protocolo
  (Los investigadores deben subir como pdf un formato que estará bajo plantillas / seguimiento. El comité debe luego poder emitir una decisión y enviar el dictamen respectivo)
3.	Reporte de evento adverso
  (Los investigadores deben subir como pdf un formato que estará bajo plantillas / seguimiento. El Comité debe luego poder enviar una comunicación por medio del sistema --email con attachment posible-- a los investigadores)
4.	Terminación del estudio
(el investigador debe poder hacer clic indicando que ha completado el estudio, escribir en una cajita que diga “Justificación”, y hacer clic en "Reporte final del estudio" para subir el attachment con el reporte)
5.	Inicio del reclutamiento
(el investigador debe poder hacer clic en una casilla que diga "Reclutamiento de participantes iniciado" / "Recruitment of participants started")
7.	Envío de documentación adicional 
(el investigador debe poder hacer clic indicando que quiere enviar documentación adicional, escribir en una cajita que diga “Explicación”, y subir la documentación adicional como attachment)

**Comment by ReneFGJr** [comment]
Please, validation of the problem

**Comment by carlasaenz** [comment]
El problema no está resuelto. Ver explicación bajo el issue #62

**Comment by carlasaenz** [comment]
Voy a cerrar este issue porque a este punto coincide con el #62
