### ISSUE TITLE
Sacar logos de OPS/OMS del código fuente

### ISSUE THREAD

**Issue by carlasaenz** [bireme/proethos#53]
Por indicación de LEG.

**Comment by ReneFGJr** [comment]
Olá Carla,

me explique melhor...

é para remover as imagens da PAHO e WHO da página inicial?

**Comment by carlasaenz** [comment]
René, tuvimos reunión con la oficina legal de OPS hoy y nos dijeron literalmente que quitemos los logos de OPS/OMS de los códigos fuente. Yo creí que era posible mantener los logos en la página inicial y quitarlos de los códigos fuente. Es esto posible? Renato, qué te parece?

**Comment by renatomurasaki** [comment]
Me parece que la cosa es quitar de los códigos-fuente y de la página,
dejando solamente el logo de ProEthos.

2015-01-23 17:40 GMT-02:00 carlasaenz <notifications@github.com>:

> René, tuvimos reunión con la oficina legal de OPS hoy y nos dijeron
> literalmente que quitemos los logos de OPS/OMS de los códigos fuente. Yo
> creí que era posible mantener los logos en la página inicial y quitarlos de
> los códigos fuente. Es esto posible? Renato, qué te parece?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bireme/proethos/issues/53#issuecomment-71252293>.
>



-- 
Renato Murasaki

**Comment by ReneFGJr** [comment]
Qual o procedimento de que devo realizar?
- Retirar o "nome" da OPS/OMS dos codigos fontes (SIM) (NÃO)?
- Remover o logo da OPS/OMS da página incial (SIM) (NÃO)?
- Remover os copyrights (no rodapé) (SIM) (NÃO)?

Obrigado,

**Comment by renatomurasaki** [comment]
Retirar apenas os logos que aparecem na homepage.

Renato

**Comment by renatomurasaki** [comment]
Retirar apenas os logos que aparecem na página inicial do ProEthos.

**Comment by ReneFGJr** [comment]
Pode me mandar qual o endereço da página?

http:// ?

**Comment by renatomurasaki** [comment]
http://proethos.homolog.bvsalud.org/login.php

Eliminar os logos da OPAS e da OMS que aparecem acima do formulário de login. Veja os logos destacados dentro do quadrado vermelho da imagem anexa.

![issue53](https://cloud.githubusercontent.com/assets/1226218/5957757/799e110e-a7a4-11e4-9468-b7758c158422.png)

**Comment by carlasaenz** [comment]
No me queda claro a qué página te refieres.
A www.paho.org/proethos<http://www.paho.org/proethos> ?

Carla Saenz, PhD
Bioethics Regional Advisor
Knowledge Management, Bioethics and Research
Pan American Health Organization

**Comment by ReneFGJr** [comment]
Renato já enviou!

Obrigado!

**Comment by carlasaenz** [comment]
Salieron de todos los idiomas menos de espanhol.
![image](https://cloud.githubusercontent.com/assets/10438060/5963406/f05caeda-a7b9-11e4-9e3a-f1772771f592.png)

**Comment by trivasf** [comment]
A mi ya no me aparecen en ningun idioma

 






From: carlasaenz
Sent: ‎Thursday‎, ‎January‎ ‎29‎, ‎2015 ‎10‎:‎23‎ ‎AM
To: bireme/proethos





Salieron de todos los idiomas menos de espanhol.
 image

**Comment by renatomurasaki** [comment]
Carla, debe ser el cache de tu browser. Intente actualizar la página
nuevamente. Para mi también no se ve más los logos en ningun idioma.

2015-01-29 16:23 GMT-02:00 carlasaenz <notifications@github.com>:

> Salieron de todos los idiomas menos de espanhol.
> [image: image]
> <https://cloud.githubusercontent.com/assets/10438060/5963406/f05caeda-a7b9-11e4-9e3a-f1772771f592.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bireme/proethos/issues/53#issuecomment-72076381>.
>



-- 
Renato Murasaki
