### ISSUE TITLE
Pagina principal en espanhol contiene creditos de la OPS en ingles. 

### ISSUE THREAD

**Issue by trivasf** [bireme/proethos#54]
Al momento, bajo "descargo de responsabilidad" y "terminos de uso",  esta como: © Pan American Health Organization, 2013. All rights reserved.  
Deberia estar como: © Organización Panamericana de la Salud, 2013. Todos los derechos reservados.

**Comment by carlasaenz** [comment]
Inglés: © Pan American Health Organization, 2013. All rights reserved.
Español: © Organización Panamericana de la Salud, 2013. Todos los derechos reservados.
Portugués:  © Organização Pan-Americana da Saúde, 2013. Todos os direitos reservados.
Francés: © Organisation Panaméricaine de la Santé, 2013. Tous droits reservé.
