### ISSUE TITLE
Create mailing list for Ethics Committee member

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/proethos#57]
Use Google Groups for managing the mailing

**Comment by viniciusandrade** [comment]
Google groups created:

https://groups.google.com/forum/#!forum/proethos-committee

**Comment by carlasaenz** [comment]
Gracias, Vinicius, pero no puedo entrar. Cómo puedo acceder al grupo / escribirle a los demás miembros?

**Comment by viniciusandrade** [comment]
Carla, hemos incluído a los miembros indicados en su ultimo email de la lista de participantes. 

Para que ud. pueda administrar al grupo es necesario que me envie un correo con su dirección de correo electrónico de google (gmail).

**Comment by carlasaenz** [comment]
Gracias Vinicius. Me imagino que tendre que crear una cuenta de Gmail porque no tengo. Espero que luego pueda manejar la lista usando mi email de paho.
Saludos,
Carla

Sent from my iPhone

On Jan 27, 2015, at 7:18 AM, viniciusandrade <notifications@github.com<mailto:notifications@github.com>> wrote:


Carla, hemos incluído a los miembros indicados en su ultimo email de la lista de participantes.

Para que ud. pueda administrar al grupo es necesario que me envie un correo con su dirección de correo electrónico de google (gmail).

—
Reply to this email directly or view it on GitHub<https://github.com/bireme/proethos/issues/57#issuecomment-71639255>.




IMPORTANT: This transmission is for use by the intended
recipient and it may contain privileged, proprietary or
confidential information. If you are not the intended
recipient or a person responsible for delivering this
transmission to the intended recipient, you may not
disclose, copy or distribute this transmission or take
any action in reliance on it. If you received this transmission
in error, please dispose of and delete this transmission. 

Thank you.

**Comment by viniciusandrade** [comment]
@carlasaenz 

Para enviar y contestar mensajes puedes utilizar normalmente su cuenta de email paho, pero para la gestíon de miembros y otras tareas administrativas del mailing list es necesario la creación de una cuenta Google.

Saludos,
Vinicus
