### ISSUE TITLE
Guia para decisiones en sistema 

### ISSUE THREAD

**Issue by trivasf** [bireme/proethos#58]
A la hora de escribir la decision de un protocolo, el Sistema da una guia para hacerlo. Cada decision arroja diferentes Casillas. Debemos revisar si las Casillas estan correctas para cada opinion. Ver abajo: (no se puede adjuntar doc de word)
1.	Aprobado
  a.	Valor social
  b.	Validez científica
  c.	Selección justa de participantes
  d.	Balance favorable de beneficios y riesgos
  e.	Consentimiento informado
  f.	Respeto por los participantes
  g.	Lista insuficiencias
  h.	dictamen_7
  i.	dictamen_8
2.	Exento
  a.	Validez científica
  b.	Selección justa de participantes
  c.	Respeto por los participantes
3.	No aprobado
  a.	Validez científica
  b.	Selección justa de participantes
  c.	Balance favorable de beneficios y riesgos
  d.	Consentimiento informado
  e.	Respeto por los participantes
  f.	Lista insuficiencias
4.	Aprobacion condicional
  a.	Selección justa de participantes
  b.	Respeto por los participantes
5.	Expedita
  a.	Valor social
  b.	Validez científica
  c.	Selección justa de participantes
  d.	Balance favorable de beneficios y riesgos
  e.	Consentimiento informado
  f.	Respeto por los participantes
  g.	Lista insuficiencias
  h.	dictamen_7
  i.	dictamen_8

**Comment by carlasaenz** [comment]
Hola! Estas son las opciones como deberían aparecer para cada alternativa de decisión. En todo caso, esto captura la reflexión y discusión y no necesariamente uno decide que todos los detalles vayan en el dictamen. Para hacer el dictamenes se abre el modelo de documento en la sección de plantillas, y se copia / pega / edita lo relevante. Luego se imprime para las firmas y se debe poder jalar el PDF de ese dictamen firmado para incluirlo en la decisión. ESTE ASPECTO (incluir el PDF del dictamen) ES DE MUCHO MÁS PRIORIDAD QUE EL TEMA DE LAS CASILLAS.

1. Exento
a. Justificación
b. Comentarios o sugerencias

2. Aprobado
a. Valor social
b. Validez científica
c. Selección justa de participantes
d. Balance favorable de beneficios y riesgos
e. Consentimiento informado
f. Respeto por los participantes
g. Otros comentarios
h. Sugerencias

3. No aprobado
a. Valor social
b. Validez científica
c. Selección justa de participantes
d. Balance favorable de beneficios y riesgos
e. Consentimiento informado
f. Respeto por los participantes
g. Otros comentarios
h. Sugerencias

4. Aprobacion condicional
a. Valor social
b. Validez científica
c. Selección justa de participantes
d. Balance favorable de beneficios y riesgos
e. Consentimiento informado
f. Respeto por los participantes
g. Otros comentarios
h. Sugerencias

**Comment by trivasf** [comment]
Creo que para adjuntar un dictamen firmado, el Sistema no explica claramente que SI esta la forma de adjuntar un archive, solamente que no esta abajo donde se esta llenando las Casillas de la decision. Bajo archivos, existe el "drop-down menu" para subir "otros" archivos. Ahi creo es donde se debe ir para adjuntar el dictamen firmado. Ver:
![como aduntar dictamen](https://cloud.githubusercontent.com/assets/10438244/5911740/7a48ba14-a57e-11e4-9ad5-6d91021af47e.jpg)

**Comment by trivasf** [comment]
Los campos de alternativas para las decisiones aun estan incorrectos. Y tampoco se puede subir un dictamen.. Ver:
![cant upload decision](https://cloud.githubusercontent.com/assets/10438244/5941290/de408ee2-a6c4-11e4-991f-eef52f59397a.jpg)

**Comment by trivasf** [comment]
Tampoco me esta permitiendo llenar los campos de la decision y emitir una decision final. Ver:
![no se puede crear decision](https://cloud.githubusercontent.com/assets/10438244/5941365/6a726b4c-a6c5-11e4-977f-c8cb535a798e.jpg)

**Comment by viniciusandrade** [comment]
Tania,

Creo que el error en la opción de subir un nuevo archivo era relativo a una configuración en nuestro servidor y ya debe estar resuelto.

Podrias confirmar si ahora es posible subir nuevos archivos en este modulo del sistema?

Gracias,
Vinicius

**Comment by trivasf** [comment]
Vinicius,

Gracias por tu correo. Ya pude subir un documento de dictamen. Lo que continua incorrecto es que en el Sistema sigue poniendo todos los protocolos con decision como Aprobados, aunque se hayan decidido como No aprobados o Exentos.

Tania






From: viniciusandrade
Sent: ‎Wednesday‎, ‎January‎ ‎28‎, ‎2015 ‎8‎:‎45‎ ‎AM
To: bireme/proethos
Cc: Tania Flores





Tania,

Creo que el error en la opción de subir un nuevo archivo era relativo a una configuración en nuestro servidor y ya debe estar resuelto.

Podrias confirmar si ahora es posible subir nuevos archivos en este modulo del sistema?

Gracias,
Vinicius

**Comment by viniciusandrade** [comment]
Tania, gracias por la verificación del upload.

**Comment by trivasf** [comment]
Puede subirse el document de dictamen bien. Pero, lo que sigue estando mal, son la opciones de las alternativas de decision, que Carla comento hace 3 dias (ver arriba). 
Tambien continua incorrecto el texto de la decision que aparece en la esquina superior derecha de la pagina del protocol, bajo "estado", TODAS las pruebas dicen aprobadas, cuando todas han recibido una decision diferente.

**Comment by trivasf** [comment]
Varios errors al tomar una decision sobre un protocolo y subir un dictamen:
1. La guia para la revision interna continua teniendo las opciones equivocadas
2. Al querer subir el dictamen, las opciones de tipo de document que se subira son solamente dos: sin definer y dictamen interino. No da la opcion de decir que es el dictamen final.
Luego al tomar la decision y enviar el dictamen, los archivos que aparecen en la pagina del protocolo son: Dictamen emitido por otro comite (cuando este deberia ser el dictamen final que acaba de subirse), protocolo, y luego el archive que se subio junto con el protocolo.
3. En la pagina del protocolo bajo :"tipo de protocolo" dice Enmienda y no protocolo de investigacion o ensayo clinic como deberia decir.
4. Aunque esta prueba en particular (trewq) fue decidida como "no aprobada", el estado dice "Investigacion" y no finalizada o rechazada, como deberia decir.
5. Bajo el listado de investigaciones con decision, aunque esta prueba en particular fue "no aprobada", el Sistema la muestra, como el resto que se han decidido, como "aprobadas"

**Comment by trivasf** [comment]
Ninguno de estos puntos ha sido resuelto.

**Comment by trivasf** [comment]
Revisamoz y est funcionando correctamente. Cerramos issue
