### ISSUE TITLE
PDF de protocolo incluye mensaje de "Descripción de la actividad" que no tiene sentido

### ISSUE THREAD

**Issue by carlasaenz** [bireme/proethos#59]
Bajo las actividades incluidas dice: 
Total de 2 in_taks 1meses

Debería decir Total de X actividades en Y meses? O nada?

**Comment by trivasf** [comment]
Esto se ha reportado tambien bajo un email enviado a todos y subido por Renato como issue de varios pendientes. Aun sigue asi en el PDF y no deberia decir nada creo yo

**Comment by carlasaenz** [comment]
Ah, ok. No me di cuenta. Cómo vas? Estoy ahorita por hacer una prueba de screening porque sometí una propuesta nueva. Fingers crossed!

Carla Saenz, PhD
Bioethics Regional Advisor
Knowledge Management, Bioethics and Research
Pan American Health Organization

**Comment by trivasf** [comment]
Si! Me imagine. Pero aun no esta arreglado asi que igual.
Estoy haciendo prueba con un nuevo usuario para recibir los emails en mi correo, pero no estoy recibiendo emails del sistema cuando  entro a "olvidar contrasenha".
Luego subo los resultados.
T

Please pardon any typos. Sent from my iPhone.

**Comment by trivasf** [comment]
Esto sigue sin resolverse.

**Comment by trivasf** [comment]
Sigue sin resolverse

**Comment by trivasf** [comment]
Este mensaje continua apareciendo bajo calendario - descripcion de la actividad. Ver
![descripcion de la actividad2](https://cloud.githubusercontent.com/assets/10438244/6856222/812f1f22-d3cc-11e4-8746-fa37a9710199.jpg)

**Comment by trivasf** [comment]
Este issue continua

**Comment by trivasf** [comment]
Resuelto. Cerramos issue
