### ISSUE TITLE
Creacion de nuevo usuario y uso de opcion "olvido contrasenha" no funciona

### ISSUE THREAD

**Issue by trivasf** [bireme/proethos#60]
Cree un Nuevo usuario para realizer pruebas y recibir emails, etc... pero el Sistema no reconoce el Nuevo usuario (aunque el Sistema dice que el usuario ha sido validado) y al ir a la opcion de olvido contrasenha, el Sistema no envia ningun correo con la info de la contrasenha.

**Comment by carlasaenz** [comment]
Yo pude crear un nuevo usuario hoy. Recibí el email sin problemas (sender Root user, subject Registro exitoso). Sin embargo el link que vino en el email no funcionaba: 
http://www.paho.org/proethos//login_user_valid.php?dd1=csaenzb@yahoo.com&dd90=da9fad0d37

**Comment by trivasf** [comment]
Cree otro usuario y me paso lo mismo que a ti. Me llego el mensaje del Sistema como Root User, ver:

 



Pero al querer validar el usuario con el enlace enviado, me da error. Ver:

 





From: carlasaenz
Sent: ‎Monday‎, ‎January‎ ‎26‎, ‎2015 ‎11‎:‎17‎ ‎AM
To: bireme/proethos
Cc: Tania Flores





Yo pude crear un nuevo usuario hoy. Recibí el email sin problemas (sender Root user, subject Registro exitoso). Sin embargo el link que vino en el email no funcionaba: 
http://www.paho.org/proethos//login_user_valid.php?dd1=csaenzb@yahoo.com&dd90=da9fad0d37

**Comment by carlasaenz** [comment]
Sin embargo, el usuario funciona. Creo que con solo recibir el el email el usuario se activa.

Carla Saenz, PhD
Bioethics Regional Advisor
Knowledge Management, Bioethics and Research
Pan American Health Organization

**Comment by trivasf** [comment]
Entonces, podriamos cambair el email para evitar confusion? En vez de enviar un enlace para validar (aunque el email no lo menciona esto), que el email diga "su usuario ha sido creado" y ya. Te parece?

Please pardon any typos. Sent from my iPhone.

**Comment by carlasaenz** [comment]
Ya funciona la creación del nuevo usuario y la función de olvido de contrasenha, aunque el texto de los emails debe revisarse (sigue el problema con los acentos, entre otras cosas). Vamos a intentar hacerlo y abriremos un issue nuevo si hace falta.
