### ISSUE TITLE
Documentos de word adjuntos a propuestas no se pueden abrir

### ISSUE THREAD

**Issue by carlasaenz** [bireme/proethos#61]
Al hacer clic como en la documentación sometida (como parte del proceso de tamizaje) se abre un mensaje de "File conversion"/ text encoding. Al dar ok a la opción preseleccionada aparece el documento de word con "jeroglíficos" y luego el texto desformateado. Esto solo pasa con el documento de word incluido en la propuesta (el PDF de la propuesta está ok)

**Comment by trivasf** [comment]
Estoy tratando de presenter una nueva propuesta, y tampoco me acepta document de Word como archive adjunto. Y si no subo ningun archive, el Sistema no me permite presenter la propuesta.

**Comment by trivasf** [comment]
Ver:
![word doc invalido](https://cloud.githubusercontent.com/assets/10438244/5907442/cb240f18-a553-11e4-8c87-7b46ca00c48f.jpg)

**Comment by trivasf** [comment]
El mensaje es equivocado. No deberia ser "tipo de document invalid", sino deberia ser "por favor escoja el tipo de document". Me daba error porque no habia escogido que tipo de document es el que estaba tratando de subir.

**Comment by ReneFGJr** [comment]
Qual o tipo de documento que estava tentando submeter?

**Comment by carlasaenz** [comment]
Un documento de word en alguna de las varias categorías que aparecen en el drop down menu, como por ejemplo consentimiento informado.

Carla Saenz, PhD
Regional Bioethics Advisor
Department of Knowledge Management, Bioethics and Research
Pan American Health Organization
________________________________

**Comment by ReneFGJr** [comment]
O sistema está configurado para aceitar extensões abaixo, se existir alguma outra extensão favor informar:

Extension Valid: .pdf, .doc, .docx, .rdf, .ocx, .xls, .xlsx

O servidor pode estar bloqueando aquivos de tamanhos grandes, criei uma tela no admin para validação do tamanho máximo.

_system_phpinfo.php

**Comment by carlasaenz** [comment]
No se puede validar. Sigo sin poder abrir los documentos de word. El error sale exactamente igual.

**Comment by ReneFGJr** [comment]
Não consegui compreeder o problema.

pode enviar o arquivo que não consegue realizar upload?!

**Comment by carlasaenz** [comment]
Los documentos en word que el investigador adjunta a una propuesta (por ejemplo, la ficha de consentimiento informado), cuando la propuest ha dio aprobada y el investigador va a “propuestas aprobadas” ve la lista de los documentos (PDF del protocolo, PDF de la decisión, doc(s) en words adjuntos). Sin embargo cuando uno trata de abrir el doc en word no se puede. Avísame si quedó claro ahora.
Además, (esto está en otro issue pero es importante y puedes verlo cuando vayas a resolver esto), la decisión aparece como “local ethics approval” cuando debería decir “DICTAMEN”. Más improtante aún, lo que aparece como dictamen es el documento interno con las deliberaciones del comité. Ese no se debe compartir con los investigadores. Es un insumo para hacer el dictamen. El dictamen debe poder subirse como PDF porque debe tener las firmas.

Carla Saenz, PhD
Bioethics Regional Advisor
Knowledge Management, Bioethics and Research
Pan American Health Organization

**Comment by carlasaenz** [comment]
Los documentos de word (que subí bajo "other") siguen presentando errores de formato, asi que al hacer el download se abre una ventanilla de "convert file" con un menú de opciones, pero no logro que ninguna funcione.

**Comment by trivasf** [comment]
A mi tampoco me deja ver archivos de Word que he subido. Me da el siguiente mensaje:

 






From: carlasaenz
Sent: ‎Thursday‎, ‎January‎ ‎29‎, ‎2015 ‎10‎:‎34‎ ‎AM
To: bireme/proethos
Cc: Tania Flores





Los documentos de word (que subí bajo "other") siguen presentando errores de formato, asi que al hacer el download se abre una ventanilla de "convert file" con un menú de opciones, pero no logro que ninguna funcione.

**Comment by carlasaenz** [comment]
No sería más fácil si el sistema, al hacer el pdf del protocolo, incluye en este pdf también los documentos en word que han sido incluidos? Así hay solo un pdf del protoclo completo. El investigador también puede revisar su submission viendo todo lo que contiene el PDF. Ahora antes de presentar la propuesta, cuando el investigador ve el PDF, el PDF solo indica los nombres de los documentos incluidos, pero el investigador no puede comprobar si esos documentos son los correctos porque no se abren ni son parte del PDF.

**Comment by trivasf** [comment]
A mi me parece una buena idea. Asi se crea un documento completo con todo lo que el investigador presento! 








From: carlasaenz
Sent: ‎Thursday‎, ‎January‎ ‎29‎, ‎2015 ‎10‎:‎50‎ ‎AM
To: bireme/proethos
Cc: Tania Flores





No sería más fácil si el sistema, al hacer el pdf del protocolo, incluye en este pdf también los documentos en word que han sido incluidos? Así hay solo un pdf del protoclo completo. El investigador también puede revisar su submission viendo todo lo que contiene el PDF. Ahora antes de presentar la propuesta, cuando el investigador ve el PDF, el PDF solo indica los nombres de los documentos incluidos, pero el investigador no puede comprobar si esos documentos son los correctos porque no se abren ni son parte del PDF.

**Comment by carlasaenz** [comment]
En general no se pueden abrir los documentos subidos en word en ninún estadio del proceso de revisión y bajo ningún perfil. Hacer un PDF consolidado (protocolo y documentos adjuntos) puede solucionar el problema en todos los estadios.

**Comment by viniciusandrade** [comment]
@ReneFGJr 

O problema pode ser reproduzido clicando na "Propuestas bajo revisión de la secretaría" e no título da mesma "aaaaaaaaaaaaaaaaaaaa". Após realizar  o download do arquivo "paho_bioethics_penn_internships_2015.doc" e tentar abrir pelo Word o mesmo apresenta uma janela para conversão de charset do documento, e mesmo testando algumas opções o resultado é um documento ilegível.

Fizemos o teste de acesso por ssh no servidor e transferência direta do arquivo sem usar o sistema e conseguimos abrir o documento diretamente no Word.

Com base nesta informação você teria alguma ideia da causa do problema?

Vinicius

**Comment by carlasaenz** [comment]
Gracias por aclarar, Vinicius. Una buena solución a este problema (que además mejora el sistema) es que el sitema produzca un PDF que incluya (a) el PDF que se hace automáticamente llenando los campos que tenemos y (b) todos los otros documentos que acompanhan a estos campos, que un investigador sube en word o PDF.

Carla Saenz, PhD
Bioethics Regional Advisor
Knowledge Management, Bioethics and Research
Pan American Health Organization

**Comment by carlasaenz** [comment]
Un problema adicional es que el investigador llena los campos en la página #5 de la submission, que es donde se piden los archivos adjuntos, y luego de subir el adjunto todo lo que uno lleno en esa pagina (Bibliografia, contacto cientifico, etc) se borra.


Carla Saenz, PhD
Regional Bioethics Advisor
Department of Knowledge Management, Bioethics and Research
Pan American Health Organization
________________________________

**Comment by renatomurasaki** [comment]
Carla,

Para facilitar la gestión de los issues, juntamente con el análisis de los
problemas y desarrollo de las soluciones, necesitamos crear 1 issue para
cada problema y no 1 issue para muchos problemas. Lo que se puede hacer es
relacionar los problemas entre los issues. Basta poner la señal # con el
numero del issue en el comentario.

Este problema que has descrito necesita ser un nuevo issue.

Un abrazo

**Comment by carlasaenz** [comment]
OK, gracias!
En eso estoy, abriendo nuevos issues específicos.
Abrazos,
Carla

Carla Saenz, PhD
Bioethics Regional Advisor
Knowledge Management, Bioethics and Research
Pan American Health Organization

**Comment by carlasaenz** [comment]
Siguen sin poderse abrir los docs de word. El problema sigue exacto como lo describió Vinicius.

**Comment by ReneFGJr** [comment]
Deve-se remover o arquivo _db/_db_paho.php

o sistema gerou um espaço em branco no final deste arquivo, enviando junto com o aquivo do WORD.

**Comment by carlasaenz** [comment]
Resuelto!

**Comment by viniciusandrade** [comment]
Eliminados os caracteres de controle no final do arquivo mencionado.
