### ISSUE TITLE
No se puede hacer monitoreo

### ISSUE THREAD

**Issue by carlasaenz** [bireme/proethos#62]
No es posible para el investigador entrar a una propuesta aprobada para hacer cualquier actividad (reporte de eventos adeversos, solicitud de extensión o enmienda, etc). Al hacer clic en el título del protocolo o el número de identificación se va a una página de error.
(En todos los casos el título no aparece abajo de la columna rotulada "Título del protocolo" sino a la izquierda, muy pegado al número de identificación --queda confuso).

**Comment by trivasf** [comment]
Yo tambien he tratado y no puedo ingresar a una propuesta una vez es devuelta con decision.

**Comment by ReneFGJr** [comment]
Check please!

**Comment by carlasaenz** [comment]
Veo las opciones incluidas pero de manera desordenada y todavía no todas funcionales. Están en una caja que se llama Enmienda, pero se debe llamar "Acciones de seguimiento" o algo así (hacer una enmienda es una de las varias acciones posibles.  En la caja hay un drop down menu y a lado hay un botón que dice enviar enmienda. Esto se debe corregir porque el drop down menu tiene que incluir las 6 acciones posibles que mandé en un email / issue previo (las voy a buscar y copiarlas de nuevo acá). Para cada acción posible se necesitan cosas distintas. Enviar una enmienda es una posible acción de las 6, así que el botón no debe decir solo enviar enmienda. Creo que el propósito de ese botón es como hacer "enter". En todo caso, si uno le da al botón aparece el protocolo con dos opciones solamente: editar o cancelar el proyecto. Las opciones para cada acción posible (entrar información, hacer upload de documento, etc) son las que listamos en el email detallando las 6 acciones de seguimiento.

**Comment by carlasaenz** [comment]
Estoy copiando esto del issue # 52:
Para cada propuesta que ha sido ya aprobada el investigador debe ver las siguientes seis opciones (hablamos de 7 pero una es parte de la otra). que discutimos la vez pasada. Los tres primeros puntos implican un modelo de documento que los investigadores deben poder subir, y luego un impacto en el flujo porque el comité debe poder emitir una decisión (en caso #1 y #2) que puede ser de aprobación o de no aprobación, y en el caso #3 debe poder enviar una comunicación del comité.

1. Solicitud de extensión a la aprobación del protocolo (Los investigadores deben subir como pdf un formato que estará bajo plantillas / seguimiento. El comité debe luego poder emitir una decisión y enviar el dictamen respectivo)
2. Enmienda al protocolo (Los investigadores deben subir como pdf un formato que estará bajo plantillas / seguimiento. El comité debe luego poder emitir una decisión y enviar el dictamen respectivo)
3. Reporte de evento adverso (Los investigadores deben subir como pdf un formato que estará bajo plantillas / seguimiento. El Comité debe luego poder enviar una comunicación por medio del sistema --email con attachment posible-- a los investigadores)
4. Terminación del estudio (el investigador debe poder hacer clic indicando que ha completado el estudio, escribir en una cajita que diga “Justificación”, y hacer clic en "Reporte final del estudio" para subir el attachment con el reporte)
5. Inicio del reclutamiento (el investigador debe poder hacer clic en una casilla que diga "Reclutamiento de participantes iniciado" / "Recruitment of participants started")
6. Envío de documentación adicional (el investigador debe poder hacer clic indicando que quiere enviar documentación adicional, escribir en una cajita que diga “Explicación”, y subir la documentación adicional como attachment)

**Comment by trivasf** [comment]
Ya pude ingresar a una propuesta como investigador, y aunque me de el "drop-down" menu para enviar documentos, ver:
![monitoreo ok](https://cloud.githubusercontent.com/assets/10438244/5941449/f2506f0a-a6c5-11e4-91b4-523a44958003.jpg)
Cuando quiero adjuntar un documento como una enmienda en este caso, el Sistema me envia a la siguiente pagina y ya no puedo hacer nada. Ver:

![docs de monitoreo no funcionan](https://cloud.githubusercontent.com/assets/10438244/5941482/263a6ec4-a6c6-11e4-8f58-9e51033cbb88.jpg)

**Comment by carlasaenz** [comment]
Veo que ya están las 6 opciones para el seguimiento a ptorotocolos aprobados ya han sido ingresadas, sin embargo, el subtítulo de esa caja se sigue llamando "enmiendas al protocolo original". Debe llamarse: ACCIONES DE SEGUIMIENTO AL PROTOCOLO. Además, el botón para escoger la selección se llama "Enviar enmienda" y debe simplemente decir "Aceptar" (como equivalente de Enter). Ver el pantallazo
![image](https://cloud.githubusercontent.com/assets/10438060/5960496/d01ee978-a7a3-11e4-9796-030cafc491a3.png)

Además, al ingresar a alguna de las opciones (por ejemplo, enviar reporte de eventos adversos) las únicas opciones que se siguen mostrando son "editar este proyecto" y "cancelar este proyecto", en vez de las opciones específicas para cada opción posible que están ingresadas más arriba en este issue (por ejemplo, cajita para ingresar info, posibilidad de subir attachment, etc). Esas son las opciones (distintas para cada acción --ver más arriba) que deben aparecer acá:

![image](https://cloud.githubusercontent.com/assets/10438060/5960529/2a683f1a-a7a4-11e4-839b-24ef18ebc9e8.png)

**Comment by carlasaenz** [comment]
No se puede validar. Este issue (que es básicamente el mismo que el #52 ) todavía no está resuelto

**Comment by trivasf** [comment]
Yo tambien he tratado y no se puede validar. Sigo sin poder subir documentos de monitoreo. Despues de hacer click en editar este proyecto, me envia a esta pantalla, pero no me deja hacer nada despues de esto:
![monitoreo](https://cloud.githubusercontent.com/assets/10438244/5961830/26a072ae-a794-11e4-838e-83cbf8b0ddaf.jpg)

**Comment by carlasaenz** [comment]
Las opciones de monitoreo no están disponibles

**Comment by viniciusandrade** [comment]
Esperando la creación de los 6 flujos identificados em https://github.com/bireme/proethos/issues/62#issuecomment-71726717 antes de configurarlos en el Menu Administrador

**Comment by carlasaenz** [comment]
Esto se resolvió ya para el reporte de eventos adversos, pero falta para las demás acciones de monitoreo.

**Comment by trivasf** [comment]
Yo sigo sin poder acceder a mis protocolos ya con decision y tratar de hacer algun tipo de monitoreo. La pantalla que me muestra cuando entro a uno de mis protocolos con decision, no me da ninguna opcion para monitero. Ver:
![no se puede hacer monitoreo](https://cloud.githubusercontent.com/assets/10438244/6435027/5276996a-c05a-11e4-9447-293ff24da70a.jpg)

**Comment by carlasaenz** [comment]
Antes del taller en SP resolvimos esto con Renato y Vinicius para una de las "Acciones de seguimiento": el reporte de eventos adversos. Ahora no se puede hacer ninguna acción de seguimiento porque el sistema no da opción. Podemos (1) volver a tenerlo como estaba en lo que respecta a la lista de Acciones de seguimiento y el flujo del reporte de eventos adversos, y (2) hacer los cambios pendientes para las otras acciones de seguimiento?

**Comment by trivasf** [comment]
Esto esta funcionando bien ahora. Hicimos pruebas con Rene este dia y eta funcionando. Cerramos este issue.
