### ISSUE TITLE
Campos confusos en Personalizar información del comité (menú del administrador)

### ISSUE THREAD

**Issue by carlasaenz** [bireme/proethos#63]
Por ejemplo: 
Admin email tipo
Method 1 / method 2
Admin email smtp
Adming email password –qué password va aquí?
Harvesting:  Yes/no, key, info

![image](https://cloud.githubusercontent.com/assets/10438060/5908399/0511c08c-a575-11e4-85aa-887373deee63.png)

**Comment by trivasf** [comment]
Necesitamos esclarecer los campos de este menu para personalizar la info del comite. Quiza podamos poner la explicacion de los campos en portugues, para que nos sea mas facil traducir al ingles y espanhol correcto.

![personalizar info del comite](https://cloud.githubusercontent.com/assets/10438244/5989560/092fda4e-a941-11e4-9c00-ceea778317cb.jpg)

**Comment by viniciusandrade** [comment]
Tania, acerca de los campos

Method 1 / method 2
Admin email smtp
Adming email password –qué password va aquí?
Harvesting: Yes/no, key, info

Estos campos son configuraciones técnicas del servidor donde ProEthos está hospedado para que funcione el servicio de correo. Una vez configurado (hicimos eso con Rene), no se necesita cambiar más.

**Comment by viniciusandrade** [comment]
Los campos de personalización del comite está en caja "Sobre el Comité de Ética" y los campos Teléfono, Nombre del Admin y admin_email_replay. Los demás no se puede cambiar sino impacta el funcionamiento del servicio de correos del servidor.

**Comment by trivasf** [comment]
Vinicius,

Gracias! Haciendo las traducciones en el Sistema he encontrado los terminus Harvesting y Harvesting_key. Debemos entonces dejar esos terminos sin traducer?

Slds,

Tania






From: viniciusandrade
Sent: ‎Monday‎, ‎February‎ ‎2‎, ‎2015 ‎10‎:‎41‎ ‎AM
To: bireme/proethos
Cc: Tania Flores





Tania, acerca de los campos

Method 1 / method 2
Admin email smtp
Adming email password –qué password va aquí?
Harvesting: Yes/no, key, info

Estos campos son configuraciones técnicas del servidor donde ProEthos está hospedado para que funcione el servicio de correo. Una vez configurado (hicimos eso con Rene), no se necesita cambiar más.

**Comment by renatomurasaki** [comment]
Por ahora si, Tania.
Muchas gracias.

Renato

**Comment by trivasf** [comment]
De acuerdo. Gracias!
Tania

Please pardon any typos. Sent from my iPhone.

**Comment by trivasf** [comment]
Ya que estos campos Deben dejarse asi por indicaciones de Vinicius; cerramos este issue?

**Comment by trivasf** [comment]
Cerramos esto. Vinicius indico que estos campos no Deben modificarse.
