### ISSUE TITLE
Revisar emails de dictamenes que salen del sistema y tipo de decision en el sistema 

### ISSUE THREAD

**Issue by trivasf** [bireme/proethos#64]
En base a pruebas realizadas hoy, se emitio una decision "exenta" para la propuesta asdfg, pero el Sistema lo muestra como "aprobado". Esto ya lo habiamos reportado anteriormente bajo decision "condicionalmente aprobado", e igual aparece como aprobado.
Tambien el email que sale del Sistema y va al investigador al emitir una decision de "exento", el email dice "protocol devuelto para correciones".
Se debe revisar que los email templates pertenezcan a los procesos correctos.

**Comment by carlasaenz** [comment]
Creo que el sistema esta confundiendo la categoria 'protocolo con decision' (que puede ser aprobacion, exencion, aprobacion conditional o no aprobacion) con la decision misma que puede ser cualquiera de estas 4 opciones --me dejo entender? Hay que distinguir entre estas alternativas.  Esto es prioritario.

Sent from my iPhone

On Jan 26, 2015, at 8:09 PM, Tania Flores <notifications@github.com<mailto:notifications@github.com>> wrote:


En base a pruebas realizadas hoy, se emitio una decision "exenta" para la propuesta asdfg, pero el Sistema lo muestra como "aprobado". Esto ya lo habiamos reportado anteriormente bajo decision "condicionalmente aprobado", e igual aparece como aprobado.
Tambien el email que sale del Sistema y va al investigador al emitir una decision de "exento", el email dice "protocol devuelto para correciones".
Se debe revisar que los email templates pertenezcan a los procesos correctos.

—
Reply to this email directly or view it on GitHub<https://github.com/bireme/proethos/issues/64>.




IMPORTANT: This transmission is for use by the intended
recipient and it may contain privileged, proprietary or
confidential information. If you are not the intended
recipient or a person responsible for delivering this
transmission to the intended recipient, you may not
disclose, copy or distribute this transmission or take
any action in reliance on it. If you received this transmission
in error, please dispose of and delete this transmission. 

Thank you.

**Comment by carlasaenz** [comment]
Los problemas con las decisiones del sistema persisten. Tomar una decisión con respecto a la propuesta supone emitir un DICTAMEN (aprobación, aprobación condicional, no aprobación, exención) que se debe subir como PDF porque tiene que tener firmas.
La opción que da el sistema de "escribir opinión" es un insumo para hacer ese dictamen. Para escribir la opinión tienen que estar todos los campos (Valor social, validez científica, selección justa de los participantes, balance favorable de riesgos y beneficios, consentimiento informado y respeto por los participantes). Ahora, si uno marca la opción de "aprobación condicional" aparecen solo algunos de esos campos (selección justa de los participantes y respeto por los participantes). En general, estas opciones deben revisarse para que estén de acuerdo a lo que ingresé en el issue #58 

Además ahora, al tratar de guardar la decisión de aprobación condicional, aparecen dos pop ups que lo impiden (y que no se entienden): 1. "descriction is necessary" y 2. "Quant. is necessary"

**Comment by carlasaenz** [comment]
Copio del issue #58 las opciones como deberían aparecer para cada alternativa de decisión:

Exento
a. Justificación
b. Comentarios o sugerencias

Aprobado
a. Valor social
b. Validez científica
c. Selección justa de participantes
d. Balance favorable de beneficios y riesgos
e. Consentimiento informado
f. Respeto por los participantes
g. Otros comentarios
h. Sugerencias

No aprobado
a. Valor social
b. Validez científica
c. Selección justa de participantes
d. Balance favorable de beneficios y riesgos
e. Consentimiento informado
f. Respeto por los participantes
g. Otros comentarios
h. Sugerencias

Aprobacion condicional
a. Valor social
b. Validez científica
c. Selección justa de participantes
d. Balance favorable de beneficios y riesgos
e. Consentimiento informado
f. Respeto por los participantes
g. Otros comentarios
h. Sugerencias

**Comment by carlasaenz** [comment]
Al hacer la prueba para una aprobación condicional, siguen saliendo los campos incorrectos. Deben ser

Exento
a. Justificación
b. Comentarios o sugerencias

Aprobado
a. Valor social
b. Validez científica
c. Selección justa de participantes
d. Balance favorable de beneficios y riesgos
e. Consentimiento informado
f. Respeto por los participantes
g. Otros comentarios
h. Sugerencias

No aprobado
a. Valor social
b. Validez científica
c. Selección justa de participantes
d. Balance favorable de beneficios y riesgos
e. Consentimiento informado
f. Respeto por los participantes
g. Otros comentarios
h. Sugerencias

Aprobacion condicional
a. Valor social
b. Validez científica
c. Selección justa de participantes
d. Balance favorable de beneficios y riesgos
e. Consentimiento informado
f. Respeto por los participantes
g. Otros comentarios
h. Sugerencias

**Comment by trivasf** [comment]
Y la guia para el revisor tambien continua estando disponible para el investigador. 


Please pardon any typos. Sent from my iPhone.

**Comment by trivasf** [comment]
Los campos para la guia de evaluacion han sido cambiados en base a lo enviado por Carla.

**Comment by carlasaenz** [comment]
Los campos ya han sido corregidos. Está pendiente el tema de que todo esto es insumo para hacer un dictamen, pero eso esta en otros issues ya, como un tema de roles (perfil del miembro #76  , perfil del admin #77 ) y #73
