### ISSUE TITLE
Acentos en espanhol no funcionan en algunos casos

### ISSUE THREAD

**Issue by trivasf** [bireme/proethos#65]
Por ejemplo, al pie de emails que firma el Comite de Etica, aunque ya lo edite en "editar email de comunicaciones", no lo acepta el Sistema y muestra los acentos en codigo... Ver:
![acentos en espanhol](https://cloud.githubusercontent.com/assets/10438244/5911785/1c96be9c-a57f-11e4-9baf-3ad7d6ef81af.jpg)

**Comment by trivasf** [comment]
Sigue asi. Al crear el PDF de un protocolo, por ej., bajo archivos, esta Bibliografia, y este se muestra con la "i" codificada por el acento que lleva...

**Comment by trivasf** [comment]
El problema continua. El Sistema no reconoce acentos en espanhol.

**Comment by carlasaenz** [comment]
Por favor, este arreglo es necesario para poder terminar con la revisión de los textos.

**Comment by ReneFGJr** [comment]
Code page do espanhol

**Comment by trivasf** [comment]
Los acentos en espanol estan funcionando bien. Se ha solucionado. Cerramos.
