### ISSUE TITLE
Cambios realizados no se reflejan

### ISSUE THREAD

**Issue by trivasf** [bireme/proethos#66]
Continuando con las pruebas del sistema, hemos notado que al ingresar a ProEthos como Admin, se ven algunos cambios que se han hecho, aunque aun existem varios pendientes por arreglar.
Sin embargo, me ha sucedido que al entrar con mi login, aunque solamente tengo perfil de investigador, el sistema me permite ver el menu del administrador y realizar cambios como admin. PERO, los cambios que he hecho bajo el perfil de Admin, NO puedo verlos igual bajo mi perfil. 
Sera que los cambios solo los guarda el sistema bajo el perfil bajo el cual se hacen?
A Carla tambien le sucede que si entra con su perfil personal, no puede ver algunos cambios que se suponen deben haber sido cambiados ya.
Esto es urgente de resolver ya que nosotros seguimos realizando pruebas bajo los diferentes perfiles, y debemos asegurar que el sistema registre los cambios que se hagan y que sean visibles para cualquier usuario

**Comment by trivasf** [comment]
Ejemplo: Bajo el Menu del Administrador - Mensajes del Sistema - admin_utf8_convert, este  ultimo ha sido editado el texto para mostrarlo correctamente (ver imagen) 
![utf8 screenshot](https://cloud.githubusercontent.com/assets/10438244/5944612/3324fb9c-a6dd-11e4-8380-a0daa880b7a7.jpg)
, pero el Sistema no registra el cambio y sigue mostrando ese campo como admin_utf8_convert (ver imagen)
![admin_utf8_convert](https://cloud.githubusercontent.com/assets/10438244/5944614/39e5deec-a6dd-11e4-9658-29179c92b744.jpg)

**Comment by ReneFGJr** [comment]
O problema está no servidor Bireme que não possibilita a atualização dos arquivos.

Necessita liberar a pasta "message" para gravação.

Segue erro abaixo:

Necessita liberar a pasta 
Warning: fopen(messages/msg_en_US.php) [function.fopen]: failed to open stream: Permission denied in /home/apps/bvsalud.org/proethos/htdocs/_class/_class_message.php on line 252

Warning: fwrite() expects parameter 1 to be resource, boolean given in /home/apps/bvsalud.org/proethos/htdocs/_class/_class_message.php on line 253

Warning: fwrite() expects parameter 1 to be resource, boolean given in /home/apps/bvsalud.org/proethos/htdocs/_class/_class_message.php on line 254

Warning: fclose() expects parameter 1 to be resource, boolean given in /home/apps/bvsalud.org/proethos/htdocs/_class/_class_message.php on line 255
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Warning: fopen(messages/msg_es.php) [function.fopen]: failed to open stream: Permission denied in /home/apps/bvsalud.org/proethos/htdocs/_class/_class_message.php on line 252

Warning: fwrite() expects parameter 1 to be resource, boolean given in /home/apps/bvsalud.org/proethos/htdocs/_class/_class_message.php on line 253

Warning: fwrite() expects parameter 1 to be resource, boolean given in /home/apps/bvsalud.org/proethos/htdocs/_class/_class_message.php on line 254

Warning: fclose() expects parameter 1 to be resource, boolean given in /home/apps/bvsalud.org/proethos/htdocs/_class/_class_message.php on line 255
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Warning: fopen(messages/msg_fr.php) [function.fopen]: failed to open stream: Permission denied in /home/apps/bvsalud.org/proethos/htdocs/_class/_class_message.php on line 252

Warning: fwrite() expects parameter 1 to be resource, boolean given in /home/apps/bvsalud.org/proethos/htdocs/_class/_class_message.php on line 253

Warning: fwrite() expects parameter 1 to be resource, boolean given in /home/apps/bvsalud.org/proethos/htdocs/_class/_class_message.php on line 254

Warning: fclose() expects parameter 1 to be resource, boolean given in /home/apps/bvsalud.org/proethos/htdocs/_class/_class_message.php on line 255
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Warning: fopen(messages/msg_pt_BR.php) [function.fopen]: failed to open stream: Permission denied in /home/apps/bvsalud.org/proethos/htdocs/_class/_class_message.php on line 252

Warning: fwrite() expects parameter 1 to be resource, boolean given in /home/apps/bvsalud.org/proethos/htdocs/_class/_class_message.php on line 253

Warning: fwrite() expects parameter 1 to be resource, boolean given in /home/apps/bvsalud.org/proethos/htdocs/_class/_class_message.php on line 254

Warning: fclose() expects parameter 1 to be resource, boolean given in /home/apps/bvsalud.org/proethos/htdocs/_class/_class_message.php on line 255ej

**Comment by viniciusandrade** [comment]
@ReneFGJr 

Permissão na pasta messages revisada.  Favor verificar se agora é possível atualizar as mensagens pela opção do administrador.

Vinicius

**Comment by ReneFGJr** [comment]
Pode-se cambiar o nome do documento em

http://proethos.homolog.bvsalud.org/admin_document_type.php

Menu del administrador ->  Tipos de documento

**Comment by carlasaenz** [comment]
Sí, pero incluso si cambiamos los nombres (que además están en inglés) no podemos con eso asegurar que el sistema “jale” el documento correcto. Puede haber una aprobación de otro comité de ética subida como parte del proyecto. Asumimos que el dictamen iría asociado a lo que ahora se llama aprobación ética local?
Ojo que además lo que el sistema muestra como dictamen no es el dictamen…

Carla Saenz, PhD
Bioethics Regional Advisor
Knowledge Management, Bioethics and Research
Pan American Health Organization

**Comment by carlasaenz** [comment]
Gracias. Estoy haciendo los cambios. Dos preguntas:
1. Qué es”, en esa página que enviaste, “Termo de In” (código: agend)
2. Por qué aparecen todas las opciones bajo la categoría “Tipo de decisión”? Estos no son los tipos de decisión sino los documentos que pueden / deben acompanhar el envío de un protocolo.
Gracias!

Carla Saenz, PhD
Bioethics Regional Advisor
Knowledge Management, Bioethics and Research
Pan American Health Organization

**Comment by carlasaenz** [comment]
Hola René,
Cambié los nombres en espanhol pero se cambiaron en inglés también. Si voy al inglés y lo cambio ahí se cambian en espanhol también.

Carla Saenz, PhD
Bioethics Regional Advisor
Knowledge Management, Bioethics and Research
Pan American Health Organization

**Comment by viniciusandrade** [comment]
@ReneFGJr 

Há o tipo de documento que no campo Nombre tem o seguinte valor "Aprobación ética de otro comité".

Buscando este texto na tela "Mensajes del sistema", encontramos o respectivo registro, associado ao idioma espanhol. Ao tentar criar novo registro para realizar as traduções para inglês e português, o formulário que se abre não permite edição no campo "Campo" (creio que o nome é 'dd3'). Entendo que deveríamos colocar o valor "Aprobación ética de otro comité" neste campo, indicar o idioma e realizar a tradução no campo "Contenido". 

Seria este o procedimento?

**Comment by trivasf** [comment]
Los cambios ya se reflejan. Voy a cerrar este issue y abrir uno Nuevo con el issue de Carla, que el Sistema deberia anexar junto con el PDF, los archivos que se suban.
