### ISSUE TITLE
Debe poder elimentarse un registro de ensayos clínicos con las propuestas aprobadas

### ISSUE THREAD

**Issue by carlasaenz** [bireme/proethos#68]
Esto es un feature importante de ProEthos que aplica solo para los protocolos que son ensayos clínicos. Los campos obligatorios de registros de ensayos clínicos han sido incluidos y debe tenerse la posibilidad de enviar a un registro (como html?) directamente la información. Supongo que los registros deben aparecer en un drop down menu.
(Este es un tema prioritario pero de baja severidad porque no impacta otras funciones, sino solo que no se tiene una de las características clave de ProEthos hasta que no funcione)

**Comment by ReneFGJr** [comment]
Exportação dos XML da OMS

**Comment by renatomurasaki** [comment]
Se desarrollo el botón de OMS XML para los casos de ensayos clinicos - eb71a5e4d4911f23f5208e3051aaafa53314e7eb, pero presenta un error en el XML.

**Comment by wilsonmoura** [comment]
Depricated version of ProEthos. New version available at https://github.com/bireme/proethos2
