### ISSUE TITLE
No logro personalizar los logos del comité

### ISSUE THREAD

**Issue by carlasaenz** [bireme/proethos#69]
El "logo" actual es una cuadro con el nombre del comité de ética de OMS. Quise remplazarlo (por el logo de ProEthos, por poner algo) pero no lo logro usando el menú del administrador.

**Comment by trivasf** [comment]
Yo tambien he tratado, y aunque no da ningun mensaje de error, el logotipo del comite actual no puede cambiarse.

**Comment by trivasf** [comment]
Esto ya fue resuelto.
