### ISSUE TITLE
Campos duplicados bajo Menu del Administrador

### ISSUE THREAD

**Issue by trivasf** [bireme/proethos#70]
Bajo menu del administrador, existen campos duplicados o confusos:
1.  Bajo: "Registros del Sistema: 
•Campos del protocolo
•Campos del protocolo Enmiendas al protocolo original (este ultimo campo es nuevo, para enmiendas? no me queda claro cual es su funcion)
2. Comunicaciones electronicas esta duplicado 
3. Modelos de dictamentes esta duplicado y no puede ser traducido. Si se traduce bajo espanhol tambien los campos en ingles quedan en espanhol. Y viceversa.

**Comment by ReneFGJr** [comment]
Para fazer com que o sistema traduza automaticamente é necessário que insira # no início do texto.

**Comment by viniciusandrade** [comment]
@ReneFGJr 

O problema de campo duplicado  esta resolvido mas a impossibilidade de tradução permanece e já existe um ticket relacionado a este problema   https://github.com/bireme/proethos/issues/66#issuecomment-72210921
