### ISSUE TITLE
Include license disclaimer into ProEthos files header

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/proethos#72]
The license disclaimer to be included in header files is:

 ------
This file is part of the ProEthos Software.
 
Copyright 2013, PAHO. All rights reserved.

You can redistribute it and/or modify Proethos under the terms of the PROETHOS License as published by PAHO, which restricts commercial use of the Software.

ProEthos is distributed in the hope that it will be useful,but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the PROETHOS License for more details.

You should have received a copy of the Proethos License along with the ProEthos Software.  If not, see (URL).
 --------

The URL is the address to LICENSE.txt file available on ProEthos Github account.

**Comment by carlasaenz** [comment]
Gracias, Renato. Solo he editado el texto para que ProEthos esté escrito de la misma manera todas las veces que aparece:


This file is part of the ProEthos Software.

Copyright 2013, PAHO. All rights reserved.

You can redistribute it and/or modify ProEthos under the terms of the ProEhos License as published by PAHO, which restricts commercial use of the Software.

ProEthos is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the ProEthos License for more details.

You should have received a copy of the ProEthos License along with the ProEthos Software.  If not, see (URL).

Carla Saenz, PhD
Regional Bioethics Advisor
Department of Knowledge Management, Bioethics and Research
Pan American Health Organization
________________________________

**Comment by moacirmoda** [comment]
Done!
