### ISSUE TITLE
Dictamenes incorrectos

### ISSUE THREAD

**Issue by carlasaenz** [bireme/proethos#73]
Lo que aparece como dictamen (con el título de Local ethical approval) NO es el dictamen. Ese documento que se llena en el sistema es un documento interno para el Comité que puede tener información que el comité no quiera compartir con los investigadores. El dictamen oficial tiene que tener las firmas, y debe ser hecho usando este documento interno como referencia. Para que se pueda incluir un documento con firmas debe ser posible hacer un upload de un documento en PDF y marcarlo como el dictamen que el investigador debe poder leer.

**Comment by carlasaenz** [comment]
Relacionado a issue #64 aunque ese issue incluye el problema mas general que las plantillas para hacer el documento interno (que no es el dictamen) deben corregirse

**Comment by carlasaenz** [comment]
Sigo viendo el problema.
Ahora aparece la posibilidad de subir un documento, es decir el dictamen, pero no es un miembro quien puede subir un dictamen, ni tampoco asignar a otros para hacer la revision.
Solo el admin debe poder subir el dictamen y tomar la decision sobre la propuesta.

**Comment by viniciusandrade** [comment]
Esperando la resolución de los issues #62, #64 y #79 antes de nueva evaliación de este issue.

**Comment by trivasf** [comment]
Al momento, el dictamen puede ser subido por el Admin y por la Secretaria. Al subir un dictamen, el texto que se le ha asignado es "opinion interina". Pero este es un issue que tiene que ver con textos nada mas. Cada comite llamara el dictamen como bien parezca. Procedemos a cerrar este issue.
