### ISSUE TITLE
PDF del protocolo que incluya los documentos que se han anexado a la propuesta

### ISSUE THREAD

**Issue by trivasf** [bireme/proethos#74]
De Carla:
No sería más fácil si el sistema, al hacer el pdf del protocolo, incluye en este pdf también los documentos en word que han sido incluidos? Así hay solo un pdf del protoclo completo. El investigador también puede revisar su submission viendo todo lo que contiene el PDF. Ahora antes de presentar la propuesta, cuando el investigador ve el PDF, el PDF solo indica los nombres de los documentos incluidos, pero el investigador no puede comprobar si esos documentos son los correctos porque no se abren ni son parte del PDF.

**Comment by trivasf** [comment]
Esto aun no funciona asi. El PDF aunque incluye una casilla con el nombre del archive subido con el protocol, este no puede abrirse ni verse.

**Comment by trivasf** [comment]
Los archivos adjuntos a un protocol aun no se muestran cuando se crea el PDF

**Comment by trivasf** [comment]
Correccion - Al momento los investigadores pueden acceder a los archivos subidos uno por uno. Conversamos que si los investigadores suben archvios en Word por ejemplo, estos no pueden convertirse a PDF automaticamente al crear el PDF del protocolo. Carla, lo dejamos como esta?

**Comment by carlasaenz** [comment]
Creo que por ahora sí, porque esto no es prioritario. Podríamos cerrar el issue (y reabrirlo si esto vuelve a surgir sobre la base del uso y los comentarios de los comités) o recategorizarlo como de baja prioridad para evaluar la necesidad de tener un PDF completo luego.

Carla Saenz, PhD
Regional Bioethics Advisor
Department of Knowledge Management, Bioethics and Research
Pan American Health Organization
________________________________

**Comment by trivasf** [comment]
cerramos por ahora. Si en el futuro aparece esto como una prioridad o exigencia, entonces lo consideramos nuevamente.
