### ISSUE TITLE
Campos diferentes que utilizan el mismo termino

### ISSUE THREAD

**Issue by trivasf** [bireme/proethos#75]
Bajo el menu del administrador, esta el titulo Dictamenes de Protocolo, bajo el cual estan los modelos de dictamenes, Sin embargo, este titulo, tambien indica el numero de revisiones que requiere un protocolo presentado para revision. Ver imagenes. Deben separarse estos dos campos para que no esten bajo la misma descripcion.
![dictamenes de protocolo_termino equivocado](https://cloud.githubusercontent.com/assets/10438244/5989227/e4c84eae-a934-11e4-95a4-30468bc32d3d.jpg)

**Comment by trivasf** [comment]
Varios terminos siguen mal. Se usa el campo de un termino para varios campos en el Sistema y eso crea confusion.

**Comment by trivasf** [comment]
Esto sigue igual. Hay campos diferentes que utilizan el mismo termino aunque no tienen nada que ver el uno con el otro. Si se borra/edita un campo, tambien borra/edita el otro, aunque no se quiera cambiar. Ver:
![campos distintos con mismo texto](https://cloud.githubusercontent.com/assets/10438244/6562280/c3d5bfa8-c665-11e4-9a23-2eeb18f74e83.jpg)
![campos distintos con mismo texto2](https://cloud.githubusercontent.com/assets/10438244/6562479/7e8df418-c667-11e4-8fb1-7d7199bec6c6.jpg)

**Comment by trivasf** [comment]
Otro ejemplo:
Aca anteriormente decia tipo de protocol: Investigacion o Ensayo clinico. Pero en algun campo se edito esto para que leyera Enmienda, y se cambio este campo tambien!
![campos distintos con mismo texto3](https://cloud.githubusercontent.com/assets/10438244/6562897/abbd1380-c66a-11e4-838f-dac554e725b1.jpg)

**Comment by renatomurasaki** [comment]
Duplicado del #120.
