### ISSUE TITLE
Roles de miembro

### ISSUE THREAD

**Issue by carlasaenz** [bireme/proethos#76]
Los miembros del comité hacen su evaluación pero esta evaluación es un INSUMO para la discusión del comité. Los miembros no escriben el dictamen final. Los miembros tampoco pueden designar a otros revisores. Los miembros tampoco pueden ingresar decisiones sobre una propuesta.
Sin embargo los miembros (todos los miembros, no solo los designados para revisar una propuesta) deben poder ver los documentos que han sido hechos como insumos para la evaluación final, como por ejemplo las revisiones de otros miembros y del / los ad hoc.

**Comment by trivasf** [comment]
Esto esta funcionando correctamente. El perfil de miembro solo permite hacer anotaciones bajo la guia de revision, pero no pueden ingresar ninguna decision sobre la propuesta. Tambien si pueden verse los documentos de un protocol presentado bajo este perfil.
