### ISSUE TITLE
Roles de admin

### ISSUE THREAD

**Issue by carlasaenz** [bireme/proethos#77]
Solo el admin debe poder seleccionar revisores (miembros y ad hoc), ingresar una decision sobre una propuesta y enviar un parecer/dictamen a un investigador.
El parecer/dictamen NO se genera automáticamente. Lo que se genera automáticamente es un INSUMO para hacer el dictamen, que se redactará en la plantilla incluida en documentos luego de la reunión.
Durante la reunión se puede llenar un documento automático con las casillas (Valor Social, Validez científica, etc) capturando la discusión y también utilizando los otros insumos que tiene el comité.
No debe ser posible enviar "automáticamente" ninguno de estos insumos al investigador.

**Comment by trivasf** [comment]
Al momento, Admin y Secretaria muestran los mismos privilegios, de asignar revisor, evaludor externo, agenda para proxima reunion, etc.

**Comment by renatomurasaki** [comment]
Cerrado, después de la revisión de Tania y Carla durante la sesión Skype.
