### ISSUE TITLE
Corrigir erro de associação de usuario e perfil

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/proethos#79]
Usuario membro vê todas as opções de perfil administrador. Ao utilizar a função proxy no Menu Administrador, é possível verificar o perfil  membro funcionando corretamente.

**Comment by ReneFGJr** [comment]
Validade, Fix it!

**Comment by renatomurasaki** [comment]
No se reproduce más el error después de la actualización realizada en https://github.com/bireme/proethos/commit/5f4efdff35d0670643c5e75953e7539dbfc76560
