### ISSUE TITLE
No se puede logar en el sistema utilizando la información de acceso por defecto

### ISSUE THREAD

**Issue by asael-silva** [bireme/proethos#80]
Después de instalar el sistema bajo Windows no pudo acceder el sistema con el usuario 'admin' y contraseña 'proethos'. También se intentó utilizar com la caja alta como está en el documento de instalación y no logro acceder.
Mirando la base de datos se notó que la tabla de usuarios está vacía.

**Comment by asael-silva** [comment]
Borré todo y empezé nuevamente con la variable short_tag_open  del PHP configurada con 'On' y no tuve problemas. El usuario fue accepto por el sistema. La tabla de usuario no se generó en la primera vez porque hubo un fallo para identificar el código PHP. Creo que se puede cerrar ese issue.

**Comment by renatomurasaki** [comment]
Excelente esta descubierta. Me parece que se necesita actualizar el manual
de instalación para que tenga esta información de configuración del PHP,
antes de ejecutar la instalación de ProEthos.

2015-02-03 11:23 GMT-02:00 asael-silva <notifications@github.com>:

> Borré todo y empezé nuevamente con la variable short_tag_open del PHP
> configurada con 'On' y no tuve problemas. El usuario fue accepto por el
> sistema. La tabla de usuario no se generó en la primera vez porque hubo un
> fallo para identificar el código PHP. Creo que se puede cerrar ese issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bireme/proethos/issues/80#issuecomment-72648958>.
>



-- 
Renato Murasaki
