### ISSUE TITLE
Cuando una propuesta es rechazada el investigador debe poder corregir los archivos adjuntos también

### ISSUE THREAD

**Issue by carlasaenz** [bireme/proethos#81]
Si el admin no valida una propuesta sometida y la retorna al investigador, el investigador debe no solo poder corregir los campos del protocolo, sino también corregir (eliminar) los adjuntos porque, por ejemplo, es posible que la propuesta sea retornada porque el investigador incluyó un documento equivocado.

**Comment by trivasf** [comment]
Al momento los investigadores pueden acceder a los archivos subidos uno por uno. Conversamos que si los investigadores suben archvios en Word por ejemplo, estos no pueden convertirse a PDF automaticamente al crear el PDF del protocolo. Carla, lo dejamos como esta?

**Comment by carlasaenz** [comment]
Creo que por ahora sí, porque esto no es prioritario. De hecho ameritaría cerrar el issue (tomando en cuenta el título) y pensar si está justificado abrir un nuevo issue sobre el tema del PDF sobre la base del uso y los comentarios de los comités.

Carla Saenz, PhD
Regional Bioethics Advisor
Department of Knowledge Management, Bioethics and Research
Pan American Health Organization
________________________________

**Comment by trivasf** [comment]
Disculpas. Este comentarionlo envir bajo el issue equivocado. Este comentario es para el issue #74

Please pardon any typos. Sent from my iPhone

**Comment by trivasf** [comment]
las enmiendas no estan funcionando correctamente. Los protocolos originales si. Revisamos ahora.

**Comment by trivasf** [comment]
Esto esta funcionando ya correctamente. Cerramos.
