### ISSUE TITLE
Al subir un documento adjunto a un protocolo se borra la información en esa página

### ISSUE THREAD

**Issue by carlasaenz** [bireme/proethos#82]
como Bibliografía, etc. Al subir el documento se borra lo que uno ingresó en las casillas previas, de modo que uno tiene que ingresar esa información de nuevo.

**Comment by trivasf** [comment]
He hecho pruebas con esto y ya no se esta dando este problema. Ahora puedo subir el documento y la informacion ingresada en las Casillas queda guardada.
