### ISSUE TITLE
No permitir el acceso directo por URL a los archivos de la pasta documents

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/proethos#84]
Adicionar no momento de criação de novos diretórios abaixo da pasta documents um arquivo .htaccess com a seguinte instrução:

deny from all

**Comment by ReneFGJr** [comment]
Na criação do diretório bloqueia acesso com o .htaccess

	/* conteudo do arquivo */
	$content = 'deny from all';					
					
	/* Bloqueia todo acesso */
	$rlt = fopen($dir.'/.htaccess','w');
	frite($rlt,$content);
	fclose($rlt);
