### ISSUE TITLE
Borrar pestanha (tab) para las acciones de monitoreo

### ISSUE THREAD

**Issue by carlasaenz** [bireme/proethos#85]
Esta pestanha corresponde al proceso de envío inicial de la propuesta, mas no corresponde a las acciones de monitoreo de las propuestas aprobadas.
![screen shot 2015-02-03 at 6 25 44 pm](https://cloud.githubusercontent.com/assets/10438060/6028634/1f36dc28-abd2-11e4-913d-dce4fe77536e.png)

**Comment by carlasaenz** [comment]
Me refiero a la pestanha superior azul que dice "Información preliminar, Sobre el proyecto, Procedimientos...."

**Comment by carlasaenz** [comment]
Hay también que cambiar el título abajo de la pestanha. Dice "Presentación de protocolo de investigación" pero debe decir "Acción de monitoreo".

**Comment by carlasaenz** [comment]
Hay que también borrar "estoy de acuerdo con los términos..." con casilla para marcar en la última (tercera) página que hace parte del reporte de evento adverso, y también cambiar la pantalla de Presentación exitosa del protocolo que aparece luego. Debe decir "Acción de monitoreo completado".
![screen shot 2015-02-03 at 7 08 04 pm](https://cloud.githubusercontent.com/assets/10438060/6029475/0916b822-abd8-11e4-8708-bc9554e130af.png)

**Comment by ReneFGJr** [comment]
Barra de status mudar para ação de monitoreo!

**Comment by renatomurasaki** [comment]
Las acciones de monitoreo ahora presentan 3 pestañas y no más las 6 anteriores relacionadas a la sumisión del proyecto. El título de la página, abajo de las pestañas fue borrado, teniendo en cuenta que lo mismo se repite abajo en el formulario. Ahora el mensaje final del proceso es configurable tambien.

**Comment by renatomurasaki** [comment]
Pruebas hechas con Tania en problema resuelto.
