### ISSUE TITLE
Añadir en el rol de documentos a subir

### ISSUE THREAD

**Issue by sssurugi** [bireme/proethos#91]
Se sugiere añadir en el rol de documentos a subir:
1. Justificación de dispensa del consentimiento
2. Bibliografia
3. Asentimiento
4. Aval o aprobación cientifica
5. Material de Reclutamiento/Informaciones al participante
6. Aval o autorización institucional

**Comment by carlasaenz** [comment]
Esto se resolvió durante la reunión en Sao Paulo. Procedo a cerrar el ticket.
