### ISSUE TITLE
Investigador debria aparecer automatico

### ISSUE THREAD

**Issue by sssurugi** [bireme/proethos#92]
El nombre de uno de los investigadores debría ser siempre el de quien propone el proyecto, así el nombre de quien hizo el login debría aparecer automaticamente como investigador (no necesariamente el investigador principal).

**Comment by trivasf** [comment]
Mi humilde opinion es que quiza no debamos llamarlo investigador al que sube el protocolo, porque muchas veces puede que el asistente de un investigador presente el protocolo si, por ejemplo, el investigador esta de viaje... Quiza podemos agregar automaticamente al que sube el protocolo llamandolo de otra forma. Quiza "Agente que presenta", "Submitting agent"?

**Comment by sssurugi** [comment]
Es que los datos sometidos deben ser fieles al protocolo que va a ser ejecutado, es decir, es eso lo que se aprueba. De este modo, quién somete un protocolo debe ser un investigador del equipo, pues tiene la responsabilidad por los datos informados. 
Por supuesto que ni sirmpre va a ser el investigador principsl, pero en mi opinión hay que ser uno de los investigadores del equipo.
Saludos
SSS

Enviado via iPad
Sergio Surugi de Siqueira, Ph.D.
