### ISSUE TITLE
funcionalidades en Tablet (Android)

### ISSUE THREAD

**Issue by sssurugi** [bireme/proethos#94]
La funcionalidad de subir archivos desde un dispositivo Android no funciona (el botón no se puede pulsar).

**Comment by trivasf** [comment]
Esto aun no funciona. Al hacer click en subir archivo, este es el mensaje que da.
![image](https://cloud.githubusercontent.com/assets/10438244/9363039/59e40498-467a-11e5-92e5-6d500122a2d1.jpg)

**Comment by sssurugi** [comment]
Yo creo que es porque en tablets con IOS estos archivos tienen que estar en
la biblioteca de fotos. Como se fueran escaneados.



2015-08-19 13:58 GMT-03:00 Tania Flores <notifications@github.com>:

> Esto aun no funciona. Al hacer click en subir archivo, este es el mensaje
> que da.
> [image: image]
> <https://cloud.githubusercontent.com/assets/10438244/9363039/59e40498-467a-11e5-92e5-6d500122a2d1.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bireme/proethos/issues/94#issuecomment-132695160>.
>



-- 
Prof. Dr. Sergio Surugi de Siqueira.

**Comment by trivasf** [comment]
Si. Debe ser eso. Te parece entonces que cerremos este issue? Ya que es una cuestion de android/IOS y no del sistema.

**Comment by trivasf** [comment]
Conversamos con Rene y decidimos cerrar este issue ya que no es problema del sistema ProEthos sino del sistema operacional de los tablets.
