### ISSUE TITLE
Campo tipo de protocolo

### ISSUE THREAD

**Issue by sssurugi** [bireme/proethos#95]
En ese campo aparece un texto "amendmet_PROPRO" (????????)

**Comment by renatomurasaki** [comment]
Probablemente arreglar traducción del mensaje.

**Comment by ReneFGJr** [comment]
Fix #95

- Traduzir os labels

amendment__PRO
amendment__AME

**Comment by carlasaenz** [comment]
Hola. No me queda claro dónde aparecen estos labels.

**Comment by carlasaenz** [comment]
Rene, que significan estos labels?

**Comment by ReneFGJ** [comment]
amendment__PRO - Protocolo de pesquisa
amendment__AME - Gestão de Pesquisa (Emenda de pesquisa / Envio de documento / Evento adverso)

**Comment by trivasf** [comment]
Estos terminos han sido traducidos en base a la info que Rene proporciono. Esta validado (la traduccion). Cerramos este issue.
